/* English translations of the French question bank. Keep rows aligned with question-bank.js. */
(() => {
  const data = {
    chapitre1: {
      title: "AI, intelligence, and approaches",
      tf: [
        ["Machine learning is a subfield of AI, but AI is not limited to machine learning.", "Think about knowledge representation, reasoning, and planning.", "AI includes several fields; machine learning is only one of them. Deep learning is in turn part of machine learning.", "AI–ML–DL hierarchy"],
        ["Deep learning and artificial intelligence are interchangeable terms.", "Place these fields in the nested-set diagram.", "Deep learning is a family of machine-learning methods, and machine learning is itself part of AI.", "AI–ML–DL hierarchy"],
        ["An AI system must learn from data in order to count as AI.", "Does the course also cover systems that use explicit facts and rules?", "No. Symbolic systems can reason from programmed knowledge and rules without statistical learning.", "AI versus learning"],
        ["A symbolic system often represents objects or relations using explicit symbols.", "Think of predicates such as parent(X,Y) and logical rules.", "Explicitly represented facts and relations can be manipulated using inference or search rules.", "Symbolic AI"],
        ["A neural network mainly encodes its knowledge as easy-to-read facts and rules.", "Where do neural networks store the patterns they learn?", "The course instead locates this knowledge in the network's parameters, weights, and activation patterns.", "Connectionist AI"],
        ["The difference between symbolic and connectionist AI is simply that only connectionism uses mathematics.", "Does the course show equations for both traditions?", "Both use mathematics. The main difference concerns how knowledge is represented and what operations are performed.", "Comparing the traditions"],
        ["A method based on symbolic representations can never learn rules from examples.", "The historical slide distinguishes a representation from how it is obtained.", "Symbolic representations can also be learned. The central distinction is the use of explicit symbols and operations on them.", "Symbols and learning"],
        ["Artificial neural networks are loosely inspired by biological neural systems without necessarily being detailed simulations of them.", "Distinguish broad inspiration from a faithful copy of the brain.", "The course clarifies that they are not detailed simulations of the human brain.", "Neural networks"],
        ["In a hybrid system, a network can recognize objects and a symbolic planner can then use that information.", "Can the two approaches cooperate within one system?", "That is the hybrid example in the course: neural-network perception followed by planning with explicit rules.", "Hybrid approaches"],
        ["The presentation claims there is a standard, universally accepted definition of intelligence.", "Is the definition presented as settled or debated?", "The course emphasizes that there is no consensus on either intelligence or AI.", "Defining intelligence"],
        ["For Russell and Norvig, acting humanly and acting rationally are different criteria.", "One is compared with a human; the other with a goal and its constraints.", "The table crosses two axes, thinking/acting and humanly/rationally, to produce four perspectives.", "Four perspectives"],
        ["The Turing Test belongs to the acting-humanly perspective.", "The test concerns externally observable behavior.", "An agent is judged by how much its behavior resembles a human's; an identical internal structure is not required.", "Turing Test"],
        ["Thinking rationally and acting rationally mean exactly the same thing in Russell and Norvig's table.", "The table distinguishes reasoning from behavior.", "Thinking rationally concerns reasoning processes; acting rationally concerns actions that pursue goals.", "Four perspectives"],
        ["A specialized AI can outperform humans at one task without having general competence across many fields.", "Specialized means limited to a domain or range of tasks.", "Performance on one specific task is not enough to establish AGI, which involves a broad range of cognitive functions.", "Narrow AI and AGI"],
        ["The course introduces deep learning early because it is important today and provides a framework for discussing other approaches and its own limitations.", "There are two pedagogical reasons, not just one.", "The current importance of deep learning and its role as a framework for comparing AI ideas and limitations explain this course order.", "Course structure"]
      ],
      mc: [
        ["Which relationship among the three fields matches the presentation's diagram?", ["AI is part of machine learning, which contains deep learning.", "Deep learning is part of AI and separate from machine learning.", "Deep learning is part of machine learning, which is itself part of AI.", "The three fields are independent."], "Imagine three nested sets, from the broadest to the most specialized.", ["This reverses the relationship: AI includes several disciplines.", "The course places deep learning inside machine learning.", "This is the inclusion relationship shown in the presentation.", "The diagram shows subfields, not independent fields."], "AI–ML–DL hierarchy"],
        ["A program explicitly stores facts about family relationships and applies rules to infer a grandparent. Which approach is dominant?", ["Connectionist, because every relation is a pattern learned in weights.", "Symbolic, because explicit facts and rules are manipulated.", "Deep learning, because the data concerns families.", "Neither AI approach, because the result is logical."], "Look at how the knowledge is represented and how the system manipulates it.", ["The scenario does not describe learned weights.", "Explicit facts and rules are the central example of symbolic AI.", "The subject matter does not imply a deep network.", "Logical reasoning is a classic area of AI."], "Symbolic AI"],
        ["What change would make the family-relation system in the previous scenario more connectionist?", ["Add more facts that a person can read.", "Add a logical rule for each case.", "Adjust network weights from examples to produce the answers.", "Replace names with symbolic constants."], "Think about what is learned and where the patterns are encoded.", ["This increases explicit, symbolic content.", "More rules are still symbolic processing.", "Parameters adjusted during training characterize the connectionist approach.", "Changing labels does not change the approach."], "Connectionist AI"],
        ["A team claims, ‘Our model uses equations, so it is symbolic.’ What is the best response?", ["Yes: any mathematical notation defines symbolic AI.", "Not necessarily: examine the representation and operations on meaningful, explicit symbols.", "No: a symbolic method cannot contain any equations.", "Yes, if the model uses real numbers."], "The presentation warns that using mathematics is not the decisive criterion.", ["Neural networks are mathematical, but that alone does not make them symbolic in the relevant sense.", "This is the central distinction in the course.", "Symbolic systems can certainly be described mathematically.", "Real numbers appear in several families of methods."], "Comparing the traditions"],
        ["A neural robot detects a cup; a rule-based planner then decides where to put it. How should this architecture be described?", ["Symbolic only, because the task involves rules.", "Connectionist only, because a network is involved.", "Hybrid, because it combines connectionist perception with symbolic planning.", "Not AI, because it uses two approaches."], "The presence of two components does not prevent the system from being hybrid.", ["Network-based detection is also an important component.", "The planner's rules are explicit.", "The two components correspond to the traditions described in the course.", "The course explicitly says the approaches can be combined."], "Hybrid approaches"],
        ["A machine answers questions in a way that is indistinguishable from a human. Which criterion does this directly test?", ["Thinking humanly", "Acting humanly", "Thinking rationally", "Acting rationally"], "The judgment concerns observable outputs, not internal mechanisms.", ["The answer does not directly reveal a human-like thought process.", "This is the behavioral logic of the Turing Test.", "No evidence is given about the logical validity of the reasoning.", "We do not know whether the actions optimize a goal."], "Turing Test"],
        ["In Wang's account, which approach emphasizes function or input-output mapping without requiring the same concrete inputs and outputs as a human?", ["Structure-AI", "Behavior-AI", "Function-AI", "Principle-AI"], "Identify what is being compared: internal structure, observable behavior, abstract function, or general principle.", ["The structural perspective concerns states or changes comparable to the brain.", "The behavioral perspective judges external outputs that resemble a human's.", "The functional perspective compares functions or input-output mappings.", "The principle perspective concerns a general principle, such as rationality."], "Definitions of AI according to Wang"],
        ["An agent chooses at each step the action that best serves its goal, given available information and constraints. Which perspective does this illustrate?", ["Thinking humanly", "Acting humanly", "Thinking rationally", "Acting rationally"], "Ask whether the criterion concerns human resemblance or achieving a goal.", ["No comparison with human thought is indicated.", "No imitation of human behavior is required.", "The emphasis is on action rather than rules of thought.", "The action is evaluated against the goal and constraints."], "Rationality"],
        ["Why is defining AI difficult according to the course?", ["Because AI has no practical applications.", "Because the criteria depend on what intelligence means, and there is no single consensus.", "Because only conscious machines can be studied.", "Because AI includes only one method."], "Connect the difficulty to the lack of a consensual definition of intelligence.", ["The course recognizes many practical fields.", "This answer captures the definition problem.", "Consciousness is an open question, not a prerequisite for defining AI.", "The presentation covers several approaches."], "Defining AI"],
        ["Which example best refutes the claim ‘Superhuman performance in one domain proves AGI’?", ["A chess program surpasses human players but cannot perform many other cognitive tasks.", "A system competently performs several varied cognitive tasks at a human level.", "A network adjusts its parameters during training.", "A program uses logical rules."], "The key difference is the breadth of transferable abilities.", ["Success at a narrow task does not demonstrate general competence.", "This description is closer to general competence.", "Training alone does not determine the breadth of abilities.", "A symbolic representation alone says nothing about the breadth of abilities."], "Narrow AI and AGI"]
      ]
    },
    chapitre2: {
      title: "Introduction to machine learning",
      tf: [
        ["In supervised learning, each training example is associated with a target or label.", "Compare the feedback available here with unsupervised learning.", "The supervised signal includes a target for every training example.", "Supervised learning"],
        ["In unsupervised learning, training examples are provided without target labels.", "Clustering looks for structure in data without a supplied target.", "The absence of targets distinguishes unsupervised learning here.", "Unsupervised learning"],
        ["In reinforcement learning, feedback typically takes the form of rewards or returns linked to actions.", "The feedback need not be an immediate class label.", "The agent learns from its actions and feedback from the environment.", "Reinforcement learning"],
        ["In a supervised problem, a column used to calculate a prediction is the target.", "The target is what the model tries to predict; input columns are features.", "Input columns are features; the target is the answer to be predicted.", "Features and targets"],
        ["Predicting the price of a house, a numerical quantity, is a classification task.", "Is the output a category or a quantity?", "A real-valued quantity calls for regression; classification predicts categories.", "Classification and regression"],
        ["Assigning a photo a label from several species is a classification task.", "The output belongs to a discrete class.", "A class label, even one chosen from several, is a classification task.", "Classification"],
        ["Training and inference refer to the same computation and stage of the model lifecycle.", "One adjusts the model; the other uses a model that has already been adjusted.", "Training adjusts parameters; inference applies the model to produce predictions.", "Training and inference"],
        ["High accuracy measured on the same examples used to train a model guarantees good performance on new data.", "A model can memorize or overfit its training data.", "Training performance is not an independent estimate of generalization; evaluate on separate data.", "Generalization"],
        ["The test set should influence model choices during training in order to produce an honest final estimate.", "The test set should be kept out of modeling decisions.", "Decisions guided by the test set make its evaluation less independent. It estimates final performance on unused examples.", "Train-test separation"],
        ["The concepts of example, feature, and target are useful for describing a supervised dataset.", "An example is an observation; features describe its inputs.", "Each observation provides feature values and a target to learn in supervised learning.", "Supervised data"],
        ["If a classifier is trained on labels, its performance is necessarily evaluated correctly by measuring it on the training set.", "Training does not answer how well the model predicts unseen cases.", "Estimate performance on held-out data that was not used to fit the model.", "Evaluation"],
        ["A stratified split aims to approximately preserve class proportions across subsets.", "This does not turn evaluation into training.", "Stratification helps maintain similar class proportions across the splits.", "Stratified split"],
        ["Personalized recommendations that improve from user feedback can illustrate machine learning.", "The presentation's examples connect adaptation to data or feedback.", "Recommendation systems are an example of problems to which learning can be applied.", "Applications of ML"],
        ["The target variable can be numerical or categorical, depending on the supervised task.", "Connect the kind of output to the type of problem.", "Numerical targets generally indicate regression; categories indicate classification.", "Target type"],
        ["Changing the random seed of a split can change the test observations and the resulting score.", "The composition of a sample affects an empirical measurement.", "The presentation suggests trying different random_state values; the score may vary with the tested observations.", "Evaluation variability"]
      ],
      mc: [
        ["A model receives emails already labeled ‘spam’ or ‘legitimate’ and learns to classify them. What type of learning is this?", ["Supervised", "Unsupervised", "Reinforcement", "Inference without learning"], "Check whether each example already has a target answer.", ["Each email has a target label.", "The scenario explicitly provides labels.", "No interaction with rewards is mentioned.", "The system fits a model from labeled examples."], "Supervised learning"],
        ["An algorithm groups similar observations when no categories have been provided. Which description fits?", ["Supervised classification", "Unsupervised learning", "Supervised regression", "Inference from known labels"], "No target is provided at the outset.", ["Supervised classification normally uses labels.", "Grouping without labels is unsupervised.", "Supervised regression requires a numerical target.", "No known labels are mentioned."], "Unsupervised learning"],
        ["A robot tries an action and receives a reward based on the outcome. Which learning signal is most directly described?", ["A numerical target provided for every example", "A known category for every observation", "A reward linked to the action", "No feedback"], "Think about feedback from interaction with the environment.", ["One target per observation describes supervised learning.", "A class label per observation describes supervised learning.", "Rewards following actions are typical of reinforcement learning.", "A reward is feedback."], "Reinforcement learning"],
        ["In a housing table, area and number of bedrooms are used to predict price. What is the role of price?", ["An input feature", "Necessarily an identifier", "An observation", "The target"], "It is the value the model is asked to output.", ["Input features here include area and bedrooms.", "Nothing indicates that price is an identifier.", "An entire row would be an observation.", "Price is the quantity being predicted."], "Features and targets"],
        ["Which task is a regression task?", ["Determine whether a message is spam", "Predict the duration of a trip in minutes", "Identify a penguin species", "Assign a document to a category"], "Is the predicted variable a numerical quantity or a class?", ["This output is a category.", "A duration is a numerical quantity.", "A species is a category.", "Assigning a category is classification."], "Classification and regression"],
        ["A model has already been trained. A new penguin is shown to it, and it predicts the species. Which stage is happening?", ["Training", "Inference", "Cross-validation", "Target creation"], "The model is already fitted; now it is being used.", ["Training adjusts parameters using data.", "Applying a model to a new input to predict is inference.", "No repeated folds are described.", "The model produces a prediction; it does not create the reference label."], "Training and inference"],
        ["A tree perfectly predicts the examples used to train it. Which conclusion is valid?", ["It will necessarily generalize perfectly.", "A test set is unnecessary.", "Evaluation on separate examples is needed to estimate performance on unseen data.", "The model was not trained."], "Performance on observed data does not directly measure unseen data.", ["Overfitting remains possible.", "Test data provide a useful estimate.", "A separate split is needed to assess generalization.", "Perfect training predictions are compatible with fitting."], "Generalization"],
        ["Why reserve a test set before comparing several models?", ["To keep a final estimate based on examples that did not guide modeling decisions.", "To artificially increase the size of the training data.", "To let the model learn the test labels.", "To guarantee the same score for every split."], "The test set is for an independent final evaluation.", ["This is the methodological reason for the split.", "A test set is held out and does not increase the training set.", "Learning the test labels compromises evaluation.", "Scores can vary with the examples."], "Train-test separation"],
        ["What is the main purpose of stratify=y in a supervised split?", ["Select the best features", "Calculate a prediction", "Train two separate models", "Approximately preserve class proportions"], "This option concerns the relative composition of the splits.", ["Stratification does not select features.", "It does not make predictions.", "It splits data but does not by itself train two models.", "It keeps class proportions approximately similar."], "Stratified split"],
        ["Which description correctly distinguishes classification and regression?", ["Classification predicts a quantity; regression predicts a category.", "Both always predict a text label.", "Classification predicts a class; regression typically predicts a numerical value.", "The difference depends only on the number of examples."], "Look at the type of target value.", ["The roles are reversed.", "Regression can produce a numerical quantity.", "This is the intended distinction.", "The task type depends on the target, not the number of examples."], "Classification and regression"]
      ]
    },
    chapitre3: {
      title: "Learning algorithms",
      tf: [
        ["A decision tree chooses successive splits based on conditions on the features.", "Each internal node poses a condition that separates examples.", "Trees organize decisions as successive tests on features.", "Decision trees"],
        ["A decision-tree split must create linear decision regions in the full space.", "Several axis-aligned splits can form a nonlinear overall boundary.", "Each simple split may be a threshold cut; their combination can form a nonlinear boundary.", "Tree boundaries"],
        ["A decision tree built by greedy choices is guaranteed to be globally optimal.", "Greedy means choosing locally without examining every future sequence of choices.", "A greedy choice optimizes the current split according to a criterion; it does not guarantee the best overall structure.", "Greedy learning"],
        ["Entropy is used to measure node impurity in the tree example from the course.", "A pure node contains examples from only one class.", "Lower entropy corresponds to more homogeneous labels; it can help evaluate a split.", "Entropy and impurity"],
        ["A useful split can be evaluated using the weighted impurity of its children.", "Child groups are not necessarily the same size.", "Weighting accounts for the relative size of the partitions created by the split.", "Choosing a split"],
        ["A tree's maximum depth can be used as a stopping condition or complexity control.", "A depth limit constrains the number of successive decisions.", "max_depth limits depth and can prevent the tree from growing excessively.", "Tree hyperparameters"],
        ["KNN necessarily builds a compact set of rules before it can make predictions.", "KNN keeps training observations and consults them for each new prediction.", "KNN is described as lazy learning: it stores observations and searches for neighbors at prediction time.", "KNN"],
        ["In KNN classification, the neighbors' labels contribute to a vote that selects the class.", "The prediction depends on the selected neighborhood.", "The classifier compares neighbors and aggregates their labels, uniformly or with weights.", "KNN voting"],
        ["With distance weighting, distant neighbors have more influence on the prediction than nearby neighbors.", "Weighting is intended to strengthen local influence.", "Distance weighting increases the influence of nearby observations.", "KNN weighting"],
        ["Feature scales can change the distances used by KNN.", "A difference with a large magnitude can dominate a distance.", "Distances are sensitive to scale; preprocessing is often important for KNN.", "Scale and distance"],
        ["A very large number of neighbors can smooth out useful local structure in KNN.", "Neighborhood size controls how much context is used.", "A large k can hide local patterns, while a small k is more sensitive to noise.", "Choosing k"],
        ["The choice of k in KNN controls how many neighbors are consulted for a prediction.", "k sets the size of the neighborhood that participates in the vote.", "A small k makes predictions more local; a large k smooths the observed structure more.", "KNN hyperparameter k"],
        ["In KNN regression, the prediction is generally based on the target values of nearby examples.", "The task predicts a quantity rather than a class.", "KNN can aggregate the neighbors' numerical targets, often by taking their mean.", "KNN regression"],
        ["Adding features without adjusting their scales can never change the neighbors' ranking.", "A distance combines numerical differences across multiple features.", "Large-scale features can dominate the distance and change which observations are nearest.", "KNN distance"],
        ["Decision-tree and KNN boundaries can differ even when the models are trained on the same dataset.", "The algorithms induce different decision rules.", "The course examples illustrate that different algorithms produce different decision boundaries.", "Comparing models"]
      ],
      mc: [
        ["A tree classifies an observation by following node conditions to a leaf. What does the path represent?", ["A random draw of weights", "A sequence of tests on features", "An average of distances", "Cross-validation"], "Internal nodes divide the space according to conditions.", ["Trees do not necessarily sample weights.", "Each branch corresponds to the outcome of successive tests.", "Distance is central to KNN, not traversing a tree.", "Cross-validation is an evaluation procedure."], "Decision trees"],
        ["A parent node contains two classes in equal proportions. A split creates one large, nearly pure child and a very small mixed child. What should be examined to judge the split?", ["Only the small child's impurity", "Only the total number of features", "The children's impurity, weighted by their relative sizes", "The row identifier"], "The course describes a weighted aggregate impurity.", ["Ignoring the large child does not measure overall quality.", "The number of features is not the criterion for this split.", "Weighting accounts for the number of examples in each child.", "Identifiers do not measure impurity."], "Entropy and impurity"],
        ["Why might a very deep tree memorize its training set without generalizing well?", ["It can create highly specific splits that also capture noise.", "Depth prevents conditional decisions.", "A deep tree becomes a KNN classifier.", "It cannot use features."], "Connect tree complexity to fitting the observed examples.", ["A complex structure can fit details that do not generalize.", "Depth allows more decisions, not fewer.", "Changing algorithms does not result from depth.", "Tree splits use features."], "Complexity and generalization"],
        ["What can changing a tree's maximum depth do?", ["Change the true labels", "Turn classification into unsupervised learning", "Force every leaf to contain one class", "Control the allowed complexity of the tree"], "max_depth is a structural model setting.", ["The parameter does not change ground truth.", "It does not change whether labels are present.", "Depth does not guarantee perfectly pure leaves.", "Depth limits the size of the tree."], "Tree hyperparameters"],
        ["In KNN, what does the model do to classify a new example?", ["Apply only a rule learned during a parametric step", "Find nearby examples and aggregate their labels", "Calculate the entropy of an entire tree", "Repeat training on unlabeled data"], "KNN defers some of its work until prediction time.", ["KNN is not mainly a list of learned split parameters.", "The neighborhood determines the class vote.", "Entropy can characterize a tree split.", "The scenario does not describe retraining."], "KNN"],
        ["With k=1, a test observation is very close to a noisy training example. Which risk is plausible?", ["The vote necessarily becomes a majority vote over the whole dataset", "Feature units disappear", "Noise in this single neighbor can determine the class", "KNN no longer needs data"], "A very small neighborhood depends heavily on local observations.", ["k=1 counts only one neighbor.", "The risk concerns neighbor choice, not units.", "A noisy neighbor can strongly influence the prediction.", "KNN retains data for prediction."], "Choosing k"],
        ["Why can standardizing features be useful before KNN?", ["To prevent a large-scale variable from artificially dominating distances", "To turn every target into a class", "To remove the need to choose k", "To guarantee zero test errors"], "Think about how distance combines numerical differences.", ["Comparable scales limit one feature's dominance.", "Scaling does not transform targets.", "k is still needed.", "No preprocessing guarantees zero errors."], "Scale and distance"],
        ["A student says, ‘KNN is expensive only during training.’ What is the best correction?", ["KNN never stores observations.", "Neighbor search and voting happen at prediction time.", "Prediction does not depend on training data.", "KNN is always faster than trees."], "The presentation calls KNN a lazy learner.", ["It retains the training examples.", "Prediction must search the stored observations.", "Distances are calculated to training observations.", "Relative cost depends on the data and settings."], "KNN cost"],
        ["What are the decision regions of a tree built with thresholds on two features?", ["Necessarily concentric circles", "Always one diagonal line", "Probabilistic regions without boundaries", "Rectangular regions whose combination can form an overall nonlinear boundary"], "Each threshold test in the illustration is aligned with an axis.", ["The course does not describe circles.", "A threshold on one feature creates a vertical or horizontal split.", "Decisions assign classes in regions.", "Combining multiple tests can create a complex boundary."], "Tree boundaries"],
        ["In a high-dimensional space, why can nearest neighbors become less informative for KNN?", ["Distances no longer exist", "Most observations become similarly far away, reducing useful contrast between distances", "KNN can no longer store examples", "Targets necessarily become continuous"], "Think about the loss of distance contrast across many dimensions.", ["A distance can still be calculated.", "This is the intuition behind the curse of dimensionality discussed in the course.", "The classifier still retains examples.", "Dimensionality does not determine target type."], "Curse of dimensionality"]
      ]
    },
    chapitre4: {
      title: "Linear regression and gradient descent",
      tf: [
        ["Regression is supervised when examples provide a numerical target to predict.", "Here the output is a real-valued quantity.", "A numerical target characterizes supervised regression.", "Regression"],
        ["A linear hypothesis combines features using parameters and a bias term.", "Coefficients determine the linear contribution of the features.", "A linear prediction function is parameterized by coefficients and usually an intercept.", "Linear hypothesis"],
        ["Mean squared error penalizes errors by their absolute value.", "Squared loss squares the error.", "MSE averages the squared differences between predictions and targets, not their absolute values.", "Mean squared error"],
        ["Minimizing MSE means seeking parameters that reduce squared residuals on the data being considered.", "A residual is the difference between a prediction and its target.", "The cost function measures error between predictions and targets.", "Regression objective"],
        ["The parameter space and input space describe the same thing.", "One contains coefficient values; the other contains examples and features.", "Parameters are learned model values; inputs are observations on which the model predicts.", "Parameter and data spaces"],
        ["Gradient descent updates parameters in the direction opposite the loss gradient.", "The gradient points toward the steepest local increase.", "Subtracting a gradient step aims for a local decrease in the objective.", "Gradient descent"],
        ["If the learning rate is exactly zero, parameters do not change during gradient updates.", "The learning rate multiplies the calculated correction.", "With a zero step size, no update is applied.", "Learning rate"],
        ["An arbitrarily large learning rate guarantees faster convergence to the minimum.", "A step that is too large can overshoot the minimum or diverge.", "The step size must be appropriate; a value that is too large can make optimization unstable.", "Learning rate"],
        ["The sign of the derivative indicates the direction in which a function locally increases or decreases.", "The derivative describes the slope at a point.", "A positive derivative means the function locally increases as the input increases; a negative one indicates the opposite.", "Derivative"],
        ["A zero gradient at a point always proves that the global minimum has been found.", "A stationary point can also be a maximum or saddle point.", "A zero gradient indicates a stationary point; by itself, it does not guarantee a global minimum.", "Stationary points"],
        ["A partial derivative measures how a function changes when one parameter varies while the others are held fixed.", "It is the multivariable version of the slope along one coordinate.", "A partial derivative quantifies change with respect to a particular parameter.", "Partial derivatives"],
        ["Batch gradient descent calculates each update using all training examples.", "The word batch refers to the number of examples contributing to one update.", "Batch updates use the entire training set.", "Batch gradient descent"],
        ["A stochastic update using one example is generally more expensive per update than calculating over the full batch.", "The per-update cost is lower for one example, but updates are noisier.", "A stochastic update is lightweight, but its direction varies more.", "Stochastic gradient descent"],
        ["Gradient descent can be evaluated by tracking how the loss changes during updates.", "The optimization objective provides a quantity that can be monitored.", "A decreasing loss indicates optimization progress, although it alone does not guarantee generalization.", "Tracking optimization"],
        ["Input normalization or scale can influence the behavior of numerical optimization.", "Scale affects slopes and the shape of loss contours.", "Feature or parameter scales influence the required step sizes and practical convergence.", "Optimization geometry"]
      ],
      mc: [
        ["A model predicts the number of minutes until a bus arrives. What kind of task matches the target?", ["Classification", "Regression", "Unsupervised clustering", "Decision without data"], "The target is a measurable number.", ["Discrete categories correspond to classification.", "A numerical duration is a regression target.", "No absence of labels is indicated.", "A model is explicitly being used."], "Regression"],
        ["A linear model predicts too low for an example. What is its residual if residual = prediction − target?", ["The prediction alone", "The target alone", "The sum of the features", "A negative number"], "Subtract a larger target from a smaller prediction.", ["You must compare the two values.", "A residual is a difference, not the target.", "Features do not replace the residual definition.", "Prediction minus target is negative when the prediction is lower."], "Residuals"],
        ["Which parameter change corresponds to a gradient descent step of size η?", ["θ ← θ − η∇J(θ)", "θ ← θ + η∇J(θ)", "θ ← J(θ) − η", "θ ← θ/∇J(θ)"], "The gradient locally points uphill in the objective.", ["Subtracting the gradient aims to decrease the loss.", "Adding the gradient follows the local increase.", "The loss is not the parameter vector.", "The rule does not divide the parameters by the gradient."], "Gradient descent"],
        ["At one step, the gradient for a parameter θ is positive and η>0. What does the descent rule do to θ?", ["It necessarily increases θ", "It leaves θ unchanged", "It decreases θ", "It replaces θ with zero"], "Apply the subtraction of η times a positive number.", ["The gradient's sign makes the step negative.", "This would hold only if the gradient or learning rate were zero.", "θ ← θ − ηg decreases when g>0.", "The formula does not force θ to zero."], "Updating a parameter"],
        ["What is the risk of a learning rate that is too high?", ["No parameter will ever be updated", "Updates may overshoot good values and oscillate or diverge", "MSE automatically becomes absolute error", "The dataset loses its labels"], "The step size controls the magnitude of each change.", ["A nonzero rate produces updates when the gradient is nonzero.", "Large steps can jump past the minimum and destabilize learning.", "The choice of loss does not change this way.", "The rate does not remove labels."], "Learning rate"],
        ["Which sentence correctly describes a partial derivative ∂J/∂θ₁?", ["The local change in J with respect to θ₁ while other parameters are fixed", "The value of J when all parameters equal one", "Average error on the test set", "The predicted target for θ₁"], "It isolates the effect of one parameter coordinate.", ["This is the interpretation of a partial derivative.", "It is not an evaluation at one particular assignment.", "It is not the entire test loss.", "A parameter is not an input to be predicted."], "Partial derivatives"],
        ["If an update is calculated on the entire training set before changing the parameters, what type is it?", ["Final test", "Inference update", "Necessarily coordinate descent", "Batch gradient descent"], "The batch here contains all examples.", ["Training optimizes the model.", "Inference does not adjust parameters.", "No sequential coordinate change is specified.", "Using all examples for one update defines the batch version."], "Batch gradient descent"],
        ["Why can stochastic updates appear more irregular?", ["They always use the test set", "They have no gradient", "Each update uses an estimate from one example or a mini-batch rather than the full training population", "They optimize a different task"], "Each step is calculated from fewer examples.", ["The test set remains reserved for evaluation.", "A gradient estimate is calculated.", "Fewer examples produce noisier updates.", "The task type is unchanged."], "Stochastic gradient descent"],
        ["Near a point, the derivative of f is negative. Which statement is most accurate?", ["f increases if x increases slightly", "f decreases if x increases slightly", "f is necessarily zero everywhere", "f necessarily reaches its global minimum"], "The slope's sign indicates local change.", ["A negative derivative indicates a downward slope as x increases.", "This is the local interpretation of a negative sign.", "The slope at one point does not describe the entire function.", "A negative slope does not establish a minimum."], "Interpreting a derivative"],
        ["Why can minimizing MSE favor large residuals more than absolute-error loss?", ["MSE ignores errors", "MSE turns errors into categories", "Squaring amplifies the contribution of large-magnitude differences", "Absolute value is always greater than a square"], "Compare 1² and 3² with their magnitudes.", ["MSE is built from the differences.", "It remains a numerical loss.", "Large errors contribute quadratically.", "This relation depends on magnitude and does not support that generalization."], "Mean squared error"]
      ]
    },
    chapitre5: {
      title: "Logistic regression",
      tf: [
        ["Logistic regression is used for classification tasks, even though its name contains ‘regression.’", "Look at the model's final output type.", "It transforms a score into a probability and then produces a class using a threshold.", "Logistic regression"],
        ["The sigmoid function transforms a real-valued score into a value between 0 and 1.", "Its outputs can be interpreted as probability scores.", "The sigmoid bounds a score in the open interval (0,1), enabling a probabilistic interpretation.", "Sigmoid"],
        ["A predicted probability of 0.8 means the predicted class must always be the negative class.", "The decision depends on the chosen threshold and which class is considered positive.", "With a typical threshold of 0.5, 0.8 exceeds the threshold and yields the positive class; other thresholds are possible.", "Threshold"],
        ["Changing the decision threshold can change predicted labels without retraining the coefficients.", "The threshold is applied after probabilities are calculated.", "The scores/probabilities stay the same; the threshold changes the rule for converting them into classes.", "Threshold"],
        ["In binary classification, the classes can be encoded using two distinct values, such as 0 and 1.", "Encoding distinguishes the two categories.", "Binary logistic regression models the probability associated with an encoded class, often 0/1.", "Binary classification"],
        ["The one-vs-rest strategy trains a single binary classifier for all classes without comparing scores.", "Each class can be compared with the others using a binary classifier.", "One classifier per class contrasts that class with all others; scores are then used to choose.", "One-vs-rest"],
        ["A multilabel classifier can assign several labels to the same observation.", "Several labels can coexist for one example.", "Multilabel differs from exclusive multiclass, where only one class is assigned.", "Classification types"],
        ["The coefficients of a logistic classifier affect the linear score calculated from the features.", "The score is a combination of input values and coefficients.", "Coefficients weight the features in the score before the sigmoid.", "Coefficients"],
        ["A positive coefficient always means the probability increases, regardless of other features and their encoding.", "The coefficient acts on a score; interpretation depends on encoding and other values.", "A positive coefficient increases the linear score as the feature increases, all else equal; the probability effect depends on position on the sigmoid.", "Interpreting coefficients"],
        ["A transformation fitted on the training set should be applied to the test set using stored statistics rather than refitting on the test set.", "The test set must remain independent.", "Fit preprocessing on training data and use transform() to apply those parameters to the test set.", "Preprocessing and test data"],
        ["In a linear binary classifier, a score of zero corresponds to a probability of 0.5 under the standard sigmoid.", "The sigmoid is symmetric around a score of zero.", "σ(0)=0.5; with a threshold of 0.5, the decision boundary is where the linear score is zero.", "Decision boundary"],
        ["Multiclass and multilabel both mean that an observation must receive several classes simultaneously.", "One allows multiple labels; the other chooses one class from several.", "Exclusive multiclass chooses one class; multilabel allows several labels to coexist.", "Classification types"],
        ["Fitting coefficients and choosing a classification threshold are conceptually distinct operations.", "One builds the model; the other converts a probability into a decision.", "The threshold can be changed after fitting to alter the decision trade-off.", "Model and decision rule"],
        ["A logistic regression trained on labeled data can be evaluated on that same data without a risk of optimistic bias.", "The model has already seen these examples during fitting.", "Evaluation on training data can overestimate generalization; keeping a separate test set is important.", "Evaluation"],
        ["One-vs-rest makes it possible to reuse a binary classifier for a multiclass problem.", "A target with several classes can be decomposed into binary comparisons.", "Train one binary output per class against the rest, then compare the scores.", "One-vs-rest"]
      ],
      mc: [
        ["A classifier calculates score s=−1 and then applies the sigmoid. What changes directly?", ["The score is transformed into a probability between 0 and 1", "The example's true class", "The learned coefficients", "The number of categories in the dataset"], "The sigmoid acts on the score produced by the model.", ["Its role is to map a score to a probability.", "The true target is known from the data; it does not change.", "This operation alone does not retrain the coefficients.", "The sigmoid alone does not add classes."], "Sigmoid"],
        ["The model predicts p=0.62 and the threshold is 0.70. What does it predict if p is the probability of the positive class?", ["Positive", "Negative", "Both labels", "No prediction is possible"], "Compare p with the threshold before assigning a label.", ["The probability does not reach the positive threshold.", "0.62 is less than 0.70.", "Threshold-based binary classification chooses one label.", "The probability and threshold are enough to decide."], "Threshold"],
        ["A service wants to assign ‘invoice,’ ‘contract,’ and ‘receipt’ categories independently, and one document may belong to two categories. What type of problem is this?", ["Exclusive binary", "Exclusive multiclass", "Regression", "Multilabel"], "Can the labels coexist for the same document?", ["More than two categories are available.", "Exclusive multiclass chooses only one category.", "The outputs are labels, not a quantity.", "Several labels can be true at once."], "Classification types"],
        ["Images are classified as cat, dog, or bird, with exactly one species per image. Which description is most accurate?", ["Multivariate regression", "Multiclass classification", "Necessarily multilabel classification", "Unsupervised learning"], "There are several possible classes, but only one per image.", ["The output is not a numerical quantity.", "More than two exclusive categories is multiclass.", "The scenario requires a single class.", "Species labels can serve as supervised targets."], "Classification types"],
        ["How does one-vs-rest handle three classes?", ["It trains one classifier per class, contrasting that class with the others.", "It merges all classes into a continuous numerical target.", "It eliminates the need for labeled data.", "It uses one shared threshold without a binary model."], "Turn the problem into several binary problems.", ["This is the one-vs-rest principle.", "The classes remain categories.", "The models are trained using labels.", "Each class gets a classifier/score to compare."], "One-vs-rest"],
        ["For a linear score s=0, what value does the standard sigmoid return?", ["0", "1", "0.5", "−0.5"], "The sigmoid is symmetric at its midpoint.", ["At negative infinity it approaches 0.", "At positive infinity it approaches 1.", "σ(0)=1/(1+1)=0.5.", "The output does not become negative."], "Sigmoid"],
        ["An analyst lowers the threshold from 0.5 to 0.3 without retraining. What effect is plausible?", ["The network weights are replaced", "All probabilities become equal", "The true labels change", "More examples may be predicted positive"], "The probability now needs to cross a lower bar.", ["A threshold does not refit parameters.", "The threshold does not recalculate the probabilities.", "Ground-truth labels do not change.", "Values between 0.3 and 0.5 now count as positive."], "Threshold"],
        ["A linear score depends on several features. What does a positive coefficient typically mean?", ["The feature has no effect in any case", "With other features and encoding fixed, increasing this feature increases the linear score", "The probability increases by a constant amount in every situation", "The target class automatically becomes positive"], "First interpret the effect on the score, before the sigmoid.", ["A zero coefficient would have no direct linear effect.", "This is the direct effect of the coefficient's sign on the score, all else equal.", "The sigmoid makes the probability change depend on the current score.", "The decision also depends on the threshold."], "Interpreting coefficients"],
        ["Each bird species is to be compared with all the others. Which binary-classification strategy is suitable?", ["Fit one model without labels", "Replace classes with their alphabetical names", "One-vs-rest", "Average the features"], "The decomposition creates a positive-versus-rest task for each class.", ["Classification still requires supervision.", "Alphabetical ordering is not a model.", "One-vs-rest extends a binary classifier to multiple classes.", "Feature averages do not define the method."], "One-vs-rest"],
        ["Why should a transformation such as a scaler be fitted on training data only?", ["To prevent test information from influencing preprocessing and the final evaluation", "To increase the number of classes", "To convert probabilities into scores", "To learn the test labels"], "The test set estimates independent performance.", ["Fitting on the test set would cause information leakage.", "Scaling does not create categories.", "A scaler transforms inputs; it does not convert probabilities to scores.", "Test targets are not used for training."], "Data leakage"]
      ]
    },
    chapitre6: {
      title: "Cross-entropy and logistic geometry",
      tf: [
        ["Binary cross-entropy can be related to the likelihood of a Bernoulli target.", "A binary target can be modeled using a Bernoulli variable.", "Minimizing negative log-likelihood gives the binary cross-entropy loss.", "Cross-entropy"],
        ["Mean squared error is always preferable to cross-entropy for training logistic regression.", "Sigmoid saturation can make the MSE gradient uninformative when a prediction is very confident and wrong.", "The presentation compares gradients and explains why logistic loss offers a more useful correction in these cases.", "Choosing a loss"],
        ["A binary logistic decision boundary occurs where the linear score reaches the value associated with the threshold.", "With threshold 0.5 and the standard sigmoid, this score value is zero.", "The threshold converts a score/probability into classes; its boundary is a linear equation in the features.", "Decision boundary"],
        ["The normal vector of a hyperplane is parallel to the decision boundary.", "It points perpendicular to the plane.", "The coefficient vector is normal to the hyperplane; it is perpendicular to the boundary.", "Linear geometry"],
        ["The linear score and logistic probability are identical quantities.", "A nonlinear function, the sigmoid, connects them.", "The score is an unbounded real number; the sigmoid transforms it into a probability between 0 and 1.", "Score and probability"],
        ["Signed distance to a boundary and the linear score can differ by a factor related to the coefficient norm.", "A linear form can be normalized to express a geometric distance.", "The unnormalized score is not by itself a Euclidean distance; the norm of the weights matters.", "Score and distance"],
        ["Two observations at the same signed distance from the boundary must have the same true class.", "Distance describes position relative to the model, not ground truth.", "Prediction depends on which side of the threshold a point lies; true labels can be misclassified on either side.", "Boundary and error"],
        ["An observation classified as negative under the threshold is on the negative side of the model's boundary.", "The predicted class is determined by the threshold, not by certainty.", "The boundary separates regions where the model assigns predicted labels.", "Logistic decision"],
        ["Cross-entropy strongly penalizes a wrong prediction made with high confidence.", "Look at the logarithm of the probability assigned to the true class.", "A very low probability for the true label produces a high log loss.", "Interpreting loss"],
        ["If the target is y=1 and the model predicts p close to 1, the binary loss is small.", "The prediction assigns high probability to the true class.", "The loss −log(p) is close to zero when p is close to 1.", "Binary loss"],
        ["If the target is y=1 and p=0, the cross-entropy loss is small because the model is certain.", "The model is certain of the wrong class in this case.", "Assigning almost zero probability to the true class leads to a very large penalty.", "Wrong confidence"],
        ["Gradient descent can train logistic regression by updating coefficients to reduce the objective.", "The model is parameterized and the loss is differentiable.", "The loss gradient gives a direction for updating the parameters.", "Logistic optimization"],
        ["In linear classification, the boundary in feature space is defined by a linear equation.", "The score before the sigmoid is a linear combination of features.", "The threshold sets the linear score equal to a constant, defining a hyperplane.", "Linear boundary"],
        ["A positive or negative signed distance can indicate which side of the boundary a point lies on.", "The sign indicates the side; the magnitude gives distance under the chosen normalization.", "Signed distance encodes the side of the boundary and geometric proximity.", "Signed distance"],
        ["Cross-entropy and MSE always produce the same gradient for a sigmoid output.", "The course specifically compares their derivatives.", "The losses have different gradients; the sigmoid derivative can weaken the MSE correction.", "Gradient and loss"]
      ],
      mc: [
        ["For y=1, which predicted probability produces the largest binary cross-entropy?", ["0.99", "0.90", "0.60", "0.01"], "Loss increases when the model assigns little probability to the true class.", ["This prediction is nearly correct and confident.", "The probability of the true class remains high.", "The loss is higher but moderate.", "The model assigns almost zero probability to the true class."], "Cross-entropy"],
        ["At threshold 0.5, which probability corresponds exactly to the binary logistic decision boundary?", ["0", "0.5", "0.75", "1"], "The boundary occurs when the sigmoid returns the threshold.", ["This corresponds to a score tending to negative infinity.", "σ(0)=0.5, so the boundary corresponds to a zero score.", "This corresponds to a positive score.", "This corresponds to a score tending to positive infinity."], "Decision boundary"],
        ["The model coefficients are w=(3,4). What is the Euclidean norm of the normal vector?", ["5", "7", "12", "25"], "Calculate the square root of the sum of squares.", ["√(3²+4²)=5, the norm of the normal vector.", "7 is the sum of the components.", "12 is the sum of squares? The sum is 25.", "25 is the sum of squares, not the norm."], "Normal vector"],
        ["One point has linear score 10 and another has score 5. Why is the first not necessarily twice as far from the boundary?", ["The score has no connection to the boundary", "Both scores are probabilities", "Geometric distance normalizes the score by the coefficient norm", "The first point must be misclassified"], "A linear score is an unnormalized quantity.", ["The score determines the side and relative position of the boundary.", "Scores are not probabilities.", "Euclidean distance depends on the size of the normal vector.", "The sign and threshold determine the class, not a ratio of distances."], "Score and distance"],
        ["A sigmoid is saturated and returns a probability near 0 for a target y=1. What problem does the course's comparison highlight with MSE?", ["MSE cannot be calculated", "MSE ignores the target", "MSE turns the task into numerical regression", "The sigmoid derivative factor can make the gradient correction very small"], "Think of the product of derivatives in the chain rule.", ["The loss is defined in this case.", "MSE compares prediction and target.", "The issue concerns classification optimization, not the label type.", "The sigmoid's near-zero derivative attenuates the MSE update."], "MSE gradient and sigmoid"],
        ["Why can cross-entropy provide a stronger correction for a very confident but wrong prediction?", ["It removes the sigmoid function", "Its derivative with respect to the score simplifies to avoid the same problematic attenuation", "It does not depend on labels", "It replaces coefficients with classes"], "The course derives negative log-likelihood and applies the chain rule.", ["The sigmoid remains central to the model.", "Differentiating the loss and sigmoid yields a useful correction.", "The target determines the loss.", "The coefficients remain the trained parameters."], "Cross-entropy and gradient"],
        ["A point's score is positive and the score threshold for the boundary is zero. What can be concluded about its predicted region?", ["It is on the positive side of the boundary", "Its true label is certainly positive", "It lies exactly on the boundary", "Its probability is necessarily 1"], "When the threshold is zero, the sign determines the model's region.", ["A positive score lies on the positive side of the decision plane.", "The true class may differ from the prediction.", "A zero score corresponds to the boundary.", "The sigmoid gives a probability between 0 and 1, not necessarily 1."], "Score and decision"],
        ["What does the normal vector of a linear boundary indicate?", ["A direction parallel to every edge of the dataset", "The true class of every example", "A direction perpendicular to the boundary and related to the coefficients", "The number of classes"], "In geometry, a normal vector is orthogonal to the hyperplane.", ["Dataset edges do not define the boundary.", "The vector does not give the true labels.", "The coefficients form the boundary's normal vector.", "That is not its role."], "Linear geometry"],
        ["For y=0, which value of p minimizes the ideal binary loss for this example?", ["1", "0.75", "0.5", "0"], "The model should assign high probability to the negative label.", ["This is maximum confidence in the wrong class.", "This is still an excessive probability for y=1.", "An uncertain prediction is not ideal.", "For y=0, p close to 0 minimizes the loss."], "Binary loss"],
        ["The decision boundary was defined by s(x)=0 at threshold 0.5. If only the threshold changes to 0.8, what describes the new boundary?", ["The model must always be retrained first", "Solve s(x)=logit(0.8), shifting the score level of the boundary", "Replace the score with MSE", "The boundary necessarily remains at s=0"], "Convert the probability threshold to a score using the inverse sigmoid.", ["Changing only the threshold does not require retraining.", "A different threshold corresponds to a different linear-score level.", "The boundary is linked to threshold and score, not a new loss.", "s=0 corresponds specifically to threshold 0.5."], "Threshold and geometry"]
      ]
    },
    chapitre7: {
      title: "Model evaluation",
      tf: [
        ["Accuracy is the proportion of all predictions that are correct.", "It reports correct predictions divided by the total number of cases.", "Accuracy=(TP+TN)/(TP+TN+FP+FN).", "Accuracy"],
        ["Precision measures, among positive predictions, the proportion that is truly positive.", "Its denominator is the number of positive predictions.", "Precision=TP/(TP+FP), answering: among the predicted positives, how many are correct?", "Precision"],
        ["Recall measures, among the true positives, the proportion the model found.", "Its denominator is the number of actually positive examples.", "Recall=TP/(TP+FN). It measures the share of actual positives detected.", "Recall"],
        ["A false positive is a negative example that the model predicts as positive.", "‘Positive’ describes the prediction; ‘false’ means it is incorrect.", "FP is negative according to ground truth but predicted positive.", "Confusion matrix"],
        ["A false negative is a positive example that the model predicts as negative.", "This is a missed positive.", "FN represents positive cases that the classifier did not detect.", "Confusion matrix"],
        ["On a highly imbalanced dataset, a model that always predicts the majority class can have high accuracy but little practical value.", "Compare the large number of negatives with recall for the rare class.", "Accuracy can hide a complete failure to detect the minority class.", "Class imbalance"],
        ["F1 combines precision and recall using their simple arithmetic mean.", "Its definition uses their harmonic mean.", "F1=2PR/(P+R), the harmonic mean of precision and recall.", "F1"],
        ["A higher decision threshold can reduce the number of positive predictions.", "Fewer scores will exceed a higher bar.", "With fixed scores, raising the threshold can only remove or preserve positive predictions, not add them.", "Threshold and metrics"],
        ["Recall and precision must always increase together as the threshold changes.", "The trade-off can make the two metrics move in opposite directions.", "A higher threshold often reduces false positives but may also increase false negatives, changing the trade-off.", "Thresholds"],
        ["A ROC curve plots the true-positive rate against the false-positive rate for several thresholds.", "It traces ranking behavior as the threshold varies.", "ROC points correspond to different thresholds and relate TPR to FPR.", "ROC"],
        ["AUROC summarizes ranking ability across thresholds rather than one decision at a fixed threshold.", "The curve spans different thresholds.", "Area under the ROC summarizes ranking quality across thresholds.", "AUROC"],
        ["A micro average aggregates contributions or counts before calculating the overall metric.", "The weighting follows the number of examples or decisions.", "Micro averaging combines class counts, giving more weight to frequent classes.", "Micro and macro"],
        ["A macro average can hide poor performance on a rare class by weighting it according to its number of examples.", "Macro averaging treats classes equally.", "Macro computes the metric per class and then takes an unweighted mean, making rare classes just as influential.", "Micro and macro"],
        ["The threshold that maximizes accuracy is necessarily best for every application.", "Error costs and operational goals can favor precision or recall.", "The threshold depends on the consequences of false positives and false negatives and the goal.", "Choosing a threshold"],
        ["A confusion matrix counts different types of errors instead of reducing them to a single accuracy value.", "Its cells separate predicted and actual classes.", "TP, FP, FN, and TN counts help interpret error types.", "Confusion matrix"]
      ],
      mc: [
        ["A classifier predicts positive 20 times, of which 15 are truly positive. What is its precision?", ["0.75: 15 true positives among 20 positive predictions", "0.25: five false positives among 20 positive predictions", "0.43: 15 true positives among 35 total examples", "1.33: 20 positive predictions divided by 15 true positives"], "Precision = true positives divided by all predicted positives.", ["Precision is TP/(TP+FP), so 15/20.", "This calculates the false-positive share among predicted positives.", "The total number of examples is not given, and this is not precision.", "This fraction reverses denominator and numerator."], "Calculating precision"],
        ["There are 30 actually positive cases, of which 24 are detected. What is recall?", ["24/30 = 0.80", "30/24 = 1.25", "24/100", "6/30 = 0.20"], "Recall divides true positives by all actual positives.", ["24 true positives out of 30 actual positives gives 0.80.", "Recall cannot exceed 1; this fraction is reversed.", "The denominator must count actual positives.", "6 is the number of false negatives, not detected true positives."], "Calculating recall"],
        ["A matrix has TP=18, FP=6, FN=12, TN=64. What is accuracy?", ["18/36", "82/100", "64/82", "18/24"], "Add correct predictions TP+TN and divide by all cases.", ["18/36 does not count all cases.", "(18+64)/(18+6+12+64)=82/100.", "This fraction omits the true positives.", "This is precision among predicted positives."], "Calculating accuracy"],
        ["A medical screening application wants to miss as few positive cases as possible. Which metric is directly relevant?", ["Recall", "Accuracy alone", "Specificity of negatives only", "AUROC at one fixed threshold"], "The goal is to reduce false negatives.", ["Recall measures the share of actual positives detected.", "Accuracy can hide missed positives.", "This metric concerns negatives and does not directly answer the goal.", "AUROC summarizes thresholds, while the need describes an operational trade-off."], "Choosing a metric"],
        ["On a dataset with 99% negative examples, an always-negative model gets 99% accuracy. What does this illustrate?", ["The model necessarily has perfect recall", "Accuracy always indicates minority-class quality", "The dataset cannot be evaluated", "High accuracy can hide zero detection of the positive class"], "Consider false negatives and the rare class.", ["Recall for positives is zero.", "Accuracy does not isolate the rare class.", "Other metrics can evaluate this problem.", "The majority class dominates the total count."], "Imbalance"],
        ["Which formula corresponds to F1?", ["(Precision + recall)/2", "Precision × recall", "2 × precision × recall /(precision + recall)", "Accuracy / recall"], "It is the harmonic mean of the two metrics.", ["This is the arithmetic mean.", "The product alone is not the formula.", "This is the harmonic mean of precision and recall.", "This relation does not define F1."], "F1"],
        ["For the same scores, the threshold changes from t=0.4 to t=0.8. Which change is guaranteed?", ["The number of predicted positives can only increase", "The number of predicted positives can only stay the same or decrease", "The true labels change", "AUROC necessarily changes"], "A higher bar removes some scores that were previously positive.", ["A stricter threshold creates no new positives.", "This is the monotonic effect of a threshold on fixed scores.", "Observed targets remain fixed.", "AUROC aggregates ranking across thresholds; choosing one threshold does not change it."], "Threshold"],
        ["For a rare class, F1 is calculated per class and then averaged without weighting by the number of examples. Which aggregation is this?", ["Micro", "Frequency-weighted", "Macro", "Overall accuracy"], "Each class has the same weight in the final average.", ["Micro aggregates counts.", "Frequency weighting is unequal.", "Macro averages class scores without weighting.", "This is not aggregated accuracy."], "Macro"],
        ["Which statement most accurately describes ROC?", ["False-positive rate as a function of recall", "Precision as a function of recall while the threshold varies", "Precision as a function of false-positive rate", "True-positive rate as a function of false-positive rate while the threshold varies"], "Each threshold gives a point relating two rates from the confusion matrix.", ["This reverses the axes and uses recall (TPR) as the horizontal axis.", "This describes a precision-recall curve.", "Precision is not the vertical axis of ROC.", "This is the functional definition of the ROC curve."], "ROC"],
        ["Two classifiers have similar AUROC, but an application must decide at one threshold and false negatives are very costly. What else should be examined?", ["Metrics at the chosen threshold, especially recall and the number of false negatives", "Training score only", "Number of features only", "Alphabetical order of classes"], "AUROC alone does not specify the operational trade-off at one threshold.", ["The threshold and error costs determine the relevant behavior.", "Training alone does not show performance on unseen examples.", "The number of features does not measure the consequences of errors.", "Label order is irrelevant."], "Interpreting metrics"]
      ]
    },
    chapitre8: {
      title: "Cross-validation and hyperparameters",
      tf: [
        ["The test set is used to select hyperparameters by comparing many configurations.", "The final test must remain untouched during selection.", "Cross-validation on training data selects configurations; the test is used for one final evaluation.", "Role of the test set"],
        ["K-fold cross-validation fits a new model at each fold.", "Learned parameters are not carried from one iteration to another.", "Each iteration fits a fresh clone on the training folds and evaluates it on the held-out fold.", "Cross-validation"],
        ["Scores from cross-validation folds are independent because the validation folds differ.", "The models share many of their training examples.", "The results are related because training sets overlap; the standard deviation is not an ordinary standard error.", "Dependence between folds"],
        ["Cross-validation directly improves model generalization rather than helping compare choices.", "It is an estimation and selection procedure.", "Cross-validation estimates a procedure and supports choices; it does not automatically improve the model.", "Role of validation"],
        ["After selecting hyperparameters, the final model can be refitted on the entire training set.", "Selection is complete before this final fit.", "GridSearchCV refits the best estimator on all training data by default.", "Final refit"],
        ["To prevent leakage, a scaler in a cross-validation pipeline is fitted only on each fold's training split.", "Validation-fold data must be transformed using state learned elsewhere.", "The pipeline fits preprocessing steps within each fold.", "Pipelines and leakage"],
        ["Running fit_transform on the full dataset before cross-validation is always leakage-free if the transformer does not use y.", "Features from future validation folds still influence the transformation.", "Even without labels, statistics calculated on the full dataset expose the validation folds.", "Data leakage"],
        ["transform applies previously learned statistics without recalculating them on new data.", "Distinguish transform from fit_transform.", "Validation/test data are transformed using the state memorized by fit on the training split.", "fit and transform"],
        ["A hyperparameter is always learned like a coefficient from the loss within one configuration.", "Coefficients are parameters; structural settings are selected beforehand.", "Hyperparameters are chosen before fitting and control model structure or the learning procedure.", "Parameters vs. hyperparameters"],
        ["A tree's max_depth, KNN's n_neighbors, and logistic regression's C are examples of hyperparameters.", "These are configuration choices evaluated during selection.", "These settings control structure or regularization; they are not coefficients fitted directly.", "Hyperparameters"],
        ["GridSearchCV systematically evaluates predefined combinations of hyperparameter values.", "It forms the Cartesian product of the candidate values.", "Grid search evaluates all supplied combinations with the same folds and metric.", "Grid search"],
        ["Random search can be useful when the search space contains many combinations.", "It provides a controlled iteration budget.", "RandomizedSearchCV samples candidates and limits the number of configurations tested.", "Random search"],
        ["Repeatedly using the same test set to modify the model preserves its role as an independent final evaluation.", "As soon as results guide decisions, the test set participates in development.", "Adaptive reuse gradually turns the test into validation and biases the final estimate.", "Reusing the test set"],
        ["The average of cross-validation fold scores may depend less on one split than a single split's score, without making the folds independent.", "Both ideas must be retained.", "Cross-validation provides multiple validations, but the training sets overlap.", "Interpreting CV scores"],
        ["Hyperparameters that interact should always be optimized separately because their effect does not depend on other settings.", "A grid can evaluate multiple settings jointly.", "Hyperparameters can interact; it can be useful to evaluate their combinations.", "Hyperparameter interactions"]
      ],
      mc: [
        ["We want to estimate a validation score five times without touching the reserved test set. Which procedure fits best?", ["Evaluate five times on the same test set and keep the best score", "Split training data into five folds and validate each model on a held-out fold", "Train on all five validation folds", "Calculate the score on the examples used for fitting"], "Each fold serves once as validation; the test set stays out of the procedure.", ["This reuses the test set and creates adaptive selection.", "This is five-fold cross-validation.", "The validation fold is held out during each fit.", "A training score does not directly measure generalization."], "Cross-validation"],
        ["An analyst runs StandardScaler.fit_transform(X) before creating the folds. What is the correct diagnosis?", ["No risk if the scaler does not look at the labels", "The classifier becomes nonlinear", "The test set is automatically independent", "Statistics from validation folds influenced the transformation"], "A scaler learns means and scales even without consulting y.", ["Feature statistics are information too.", "The model type does not change.", "The cross-validation procedure is contaminated.", "Preprocessing was fitted before separating the folds."], "Data leakage"],
        ["Which workflow correctly avoids preprocessing-statistic leakage during cross-validation?", ["Fit the pipeline on each iteration's training folds, then use transform on its validation fold", "Fit the scaler once on all data, then run CV", "Calculate statistics on test and training data together", "Transform the validation fold using its own statistics"], "Fitting of transformers must follow the fold split.", ["The pipeline repeats that separation and fitting within every fold.", "Future validation folds contribute to the statistics.", "The test loses its independence.", "The validation fold must not learn its own evaluation transform."], "Pipelines"],
        ["Which statement correctly distinguishes a parameter from a hyperparameter?", ["Coefficients are hyperparameters; number of neighbors is a learned parameter", "They are two names for the same quantity", "Parameters are fitted from data; hyperparameters are chosen to configure the model or learning process", "Hyperparameters are only labels"], "Compare learned weights with the n_neighbors setting.", ["Weights/coefficients are parameters; number of neighbors is a hyperparameter.", "The course distinguishes them explicitly.", "This is the distinction taught in the course.", "A hyperparameter configures the model; it is not the target."], "Parameters and hyperparameters"],
        ["We want to evaluate every pair of candidate values for max_depth and criterion. Which method is suitable?", ["One fit without validation", "Grid search over the product of candidate values", "Random search with an unlimited budget", "Predict on the test set before training"], "Look for a method that systematically examines predefined combinations.", ["One fit does not compare candidates.", "GridSearchCV systematically explores combinations.", "Random search samples candidates and uses a finite budget.", "The training-test order is reversed."], "GridSearchCV"],
        ["Why are the scores from five-fold cross-validation not independent?", ["They necessarily use the same validation fold", "The model transfers its weights from one fold to the next", "Labels are removed", "The fitted models share many of their training examples"], "Compare their training sets, not only their validation sets.", ["Each fold serves once as validation.", "Each fold starts from a fresh model.", "Labels are used in supervised learning.", "The training sets overlap substantially."], "Dependence between folds"],
        ["After choosing the best hyperparameters by cross-validation, what should be done before final evaluation?", ["Refit the chosen pipeline on all training data, then evaluate it once on the untouched test set", "Refit the model on the test set", "Select again based on test scores until the best is found", "Shuffle the labels"], "Selection happens first using training data.", ["This is the recommended workflow.", "The test set must not be used for fitting.", "Repeated adaptation to the test set turns it into validation.", "Labels are essential and should not be arbitrarily shuffled."], "Refitting and final test"],
        ["A student sees a disappointing test score, changes the pipeline, and evaluates it again on the same test set. What is the methodological consequence?", ["None, because the pipeline did not see y", "The score necessarily becomes lower", "The test influenced choices and is no longer an independent final evaluation", "Cross-validation becomes unnecessary"], "Even without directly fitting weights on the test set, the result can guide changes.", ["Test results can guide choices indirectly.", "The direction of change is not guaranteed.", "Feedback from the score contributed to adaptive development.", "Cross-validation remains useful for selection."], "Reusing the test set"],
        ["A team needs to compare three model families. What makes the comparison more interpretable?", ["Use different validation sets, folds, and metrics for each candidate", "Use the same training data, validation folds, and metric for the searches", "Choose winners from repeated test results", "Use training error only"], "A fair comparison limits differences to what is being compared.", ["Different conditions blur the comparison.", "The same conditions make scores comparable.", "The test set should not be reused for selection.", "Training error does not measure generalization."], "Comparing models"],
        ["When might RandomizedSearchCV be preferable to grid search?", ["When each parameter has only one value", "When every combination must be examined exhaustively at any cost", "When models have no hyperparameters", "When the full grid is too costly and the number of trials should be limited"], "Random search sets an iteration budget.", ["There is nothing to search in this case.", "Random search samples rather than exhaustively searching.", "It is used for hyperparameter spaces.", "A controlled budget makes it useful for large search spaces."], "RandomizedSearchCV"]
      ]
    }
  };
  const translations = {};
  for (const [chapter, bank] of Object.entries(data)) {
    const n = Number(chapter.replace("chapitre", ""));
    bank.tf.forEach((r, i) => translations[`ch${n}_tf${String(i+1).padStart(3,"0")}`] = ({question:r[0], hint:r[1], explanation:r[2], concept:r[3]}));
    bank.mc.forEach((r, i) => {
      const id = `ch${n}_mc${String(i+1).padStart(3,"0")}`;
      const answerIndex = window.QUESTION_BANK?.[chapter]?.find(q => q.id === id)?.answer;
      translations[id] = {question:r[0], options:r[1], hint:r[2], optionExplanations:r[3], explanation:r[3]?.[answerIndex], concept:r[4]};
    });
  }
  window.QUESTION_BANK_EN = translations;
  window.CHAPTERS_EN = Object.fromEntries(Object.entries(data).map(([key, value]) => [key, value.title]));
})();
