/*
 * Banques indépendantes de l'interface. Ajoutez ou remplacez les rangées ci-dessous;
 * l'application construit automatiquement les sessions à partir de QUESTION_BANK.
 * Format V/F: [énoncé, réponse, indice, explication, concept, difficulté, page]
 * Format QCM: [question, index correct, choix, indice, raisons par choix,
 *              concept, difficulté, page]
 */
(() => {
  const tf = (ch, n, r) => ({
    id: `ch${ch}_tf${String(n).padStart(3, "0")}`, type: "true_false",
    question: r[0], answer: r[1], hint: r[2], explanation: r[3], concept: r[4],
    difficulty: r[5], source: `Chapitre ${ch}, 0${ch}.pdf, p. ${r[6]}`
  });
  const mc = (ch, n, r) => ({
    id: `ch${ch}_mc${String(n).padStart(3, "0")}`, type: "multiple_choice",
    question: r[0], options: r[2].map((text, i) => ({ id: String.fromCharCode(65+i), text, explanation: r[4][i] })),
    answer: r[1], hint: r[3], explanation: r[4][r[1]], concept: r[5], difficulty: r[6],
    source: `Chapitre ${ch}, 0${ch}.pdf, p. ${r[7]}`
  });
  const data = {
    chapitre1: {
      title: "IA, intelligence et approches",
      tf: [
        ["L'apprentissage automatique est un sous-domaine de l'IA, mais toute l'IA ne se réduit pas à l'apprentissage automatique.",true,"Pense à la représentation des connaissances, au raisonnement et à la planification.","L'IA comprend plusieurs domaines; l'apprentissage automatique n'en est qu'un. L'apprentissage profond est à son tour une partie de l'apprentissage automatique.","Hiérarchie IA–AA–AP","easy",11],
        ["L'apprentissage profond et l'intelligence artificielle sont deux termes interchangeables.",false,"Replace ces domaines dans le schéma en ensembles emboîtés.","L'apprentissage profond est une famille de méthodes de l'apprentissage automatique, qui est lui-même dans l'IA.","Hiérarchie IA–AA–AP","easy",11],
        ["Un système d'IA doit nécessairement apprendre à partir de données pour compter comme IA.",false,"Le cours présente-t-il aussi des systèmes à faits et règles explicites?","Non. Les systèmes symboliques peuvent raisonner à partir de connaissances et de règles programmées sans apprentissage statistique.","IA versus apprentissage","medium",12],
        ["Un système symbolique représente souvent des objets ou des relations avec des symboles explicites.",true,"Pense aux prédicats parent(X,Y) et aux règles logiques.","Les faits et relations explicitement représentés peuvent être manipulés par des règles d'inférence ou de recherche.","IA symbolique","easy",12],
        ["Un réseau neuronal encode principalement ses connaissances sous forme de faits et de règles faciles à lire.",false,"Où les réseaux neuronaux stockent-ils les régularités acquises?","La présentation situe plutôt ces connaissances dans les paramètres, les poids et les motifs d'activité du réseau.","IA connexionniste","easy",18],
        ["La différence entre symbolique et connexionniste se résume au fait que seul le connexionnisme utilise les mathématiques.",false,"Le cours montre-t-il des formules dans les deux traditions?","Les deux utilisent les mathématiques. La distinction porte surtout sur la représentation des connaissances et les opérations réalisées.","Comparer les traditions","medium",13],
        ["Une méthode fondée sur des représentations symboliques ne peut jamais apprendre des règles à partir d'exemples.",false,"La diapositive historique distingue la représentation de la manière de l'obtenir.","Des représentations symboliques peuvent aussi être apprises. La distinction centrale est l'usage de symboles explicites et d'opérations sur eux.","Symboles et apprentissage","hard",17],
        ["Les réseaux de neurones artificiels sont vaguement inspirés des systèmes neuronaux biologiques, sans nécessairement en être une simulation détaillée.",true,"Distingue inspiration générale et copie fidèle du cerveau.","Le cours précise qu'ils ne sont pas des simulations détaillées du cerveau humain.","Réseaux neuronaux","medium",18],
        ["Dans un système hybride, un réseau peut reconnaître des objets et un planificateur symbolique utiliser ensuite cette information.",true,"Les deux approches peuvent-elles coopérer dans le même système?","C'est l'exemple hybride présenté : perception par réseau neuronal, puis planification par règles explicites.","Approches hybrides","easy",19],
        ["La présentation affirme qu'il existe une définition standard de l'intelligence qui fait consensus.",false,"La définition est-elle présentée comme tranchée ou débattue?","Le cours souligne l'absence de consensus tant sur l'intelligence que sur l'IA.","Définir l'intelligence","easy",21],
        ["Chez Russell et Norvig, agir humainement et agir rationnellement sont deux critères différents.",true,"L'un se compare à un humain; l'autre à un objectif et ses contraintes.","Le tableau croise deux axes, penser/agir et humainement/rationnellement, qui produisent quatre perspectives.","Quatre perspectives","medium",23],
        ["Le test de Turing relève de la perspective agir humainement.",true,"Le test porte sur le comportement externe observable.","Un agent est jugé selon la ressemblance de son comportement à celui d'un humain; une structure interne identique n'est pas exigée.","Test de Turing","easy",23],
        ["Penser rationnellement et agir rationnellement désignent exactement la même chose dans le tableau de Russell et Norvig.",false,"Le tableau distingue le raisonnement et le comportement.","Penser rationnellement concerne les processus de raisonnement; agir rationnellement concerne les actions visant les objectifs.","Quatre perspectives","medium",23],
        ["Une IA spécialisée peut surpasser l'humain dans une tâche sans posséder une compétence générale dans un large éventail de domaines.",true,"Spécialisée signifie limitée à un domaine ou une gamme de tâches.","La performance dans une tâche précise ne suffit pas à établir l'AGI, définie par une vaste gamme de fonctions cognitives.","IA spécialisée et AGI","medium",28],
        ["Le cours présente l'apprentissage profond tôt parce qu'il est important aujourd'hui et fournit un cadre pour discuter d'autres approches et de ses propres limites.",true,"Il y a deux raisons pédagogiques, pas une seule.","L'importance contemporaine du deep learning et son rôle de cadre pour comparer les idées et limites de l'IA motivent cet ordre.","Ordre du cours","medium",6]
      ],
      mc: [
        ["Quelle relation entre les trois domaines correspond au schéma de la présentation?",2,["L'IA est une partie de l'apprentissage automatique, qui contient l'apprentissage profond.","L'apprentissage profond est une partie de l'IA distincte de l'apprentissage automatique.","L'apprentissage profond est une partie de l'apprentissage automatique, lui-même une partie de l'IA.","Les trois domaines sont indépendants."],"Imagine trois ensembles emboîtés, du plus large au plus spécialisé.",["Inverse la relation : l'IA contient plusieurs disciplines.","Le cours place le deep learning à l'intérieur du machine learning.","C'est l'inclusion montrée dans la présentation.","Le schéma établit des sous-domaines, pas des domaines indépendants."],"Hiérarchie IA–AA–AP","easy",11],
        ["Un programme stocke explicitement des faits sur les relations familiales puis applique des règles pour déduire un grand-parent. Quelle approche domine?",1,["Connexionniste, car toute relation est un motif appris dans des poids.","Symbolique, car les faits et règles explicites sont manipulés.","Apprentissage profond, car il s'agit de données familiales.","Aucune approche d'IA, car le résultat est logique."],"Repère où sont représentées les connaissances et comment le système les manipule.",["Le scénario ne décrit pas des poids appris.","Faits et règles explicites sont l'exemple central de l'IA symbolique.","Le domaine de données n'implique pas un réseau profond.","Le raisonnement logique est un domaine classique de l'IA."],"IA symbolique","easy",12],
        ["Quel changement rendrait le système familial du scénario précédent plus connexionniste?",2,["Ajouter davantage de faits lisibles par une personne.","Ajouter une règle logique pour chaque cas.","Ajuster des poids d'un réseau à partir d'exemples pour produire les réponses.","Remplacer les noms par des constantes symboliques."],"Pense à ce qui est appris et à l'endroit où les régularités sont encodées.",["Cela augmente le contenu explicite et symbolique.","Des règles supplémentaires restent un traitement symbolique.","Des paramètres ajustés à l'entraînement caractérisent l'approche connexionniste.","Changer les étiquettes n'altère pas l'approche."],"IA connexionniste","medium",18],
        ["Une équipe affirme : « Notre modèle emploie des équations, donc il est symbolique. » Quelle réponse est la plus juste?",1,["Oui : toute notation mathématique définit l'IA symbolique.","Pas nécessairement : il faut regarder la représentation et les opérations sur des symboles explicites porteurs de sens.","Non : une méthode symbolique ne peut contenir aucune équation.","Oui, si le modèle utilise des nombres réels."],"La présentation avertit que l'usage de mathématiques n'est pas le critère décisif.",["Les réseaux neuronaux sont mathématiques sans être pour autant symboliques au sens visé.","C'est la distinction centrale donnée dans le cours.","Les systèmes symboliques peuvent évidemment être décrits mathématiquement.","Des nombres réels apparaissent dans plusieurs familles de méthodes."],"Comparer les traditions","hard",13],
        ["Un robot neuronal détecte une tasse; un planificateur à règles choisit ensuite où la placer. Comment décrire l'architecture?",2,["Symbolique seulement, parce que la tâche implique des règles.","Connexionniste seulement, parce qu'un réseau intervient.","Hybride, car elle combine perception connexionniste et planification symbolique.","Ce n'est pas de l'IA, car deux approches sont utilisées."],"La présence de deux éléments n'empêche pas de classer le système comme hybride.",["La détection par réseau est aussi une composante importante.","Les règles du planificateur sont explicites.","Les deux composantes correspondent aux traditions décrites.","Le cours dit explicitement que les approches peuvent être combinées."],"Approches hybrides","medium",19],
        ["Une machine répond à des questions de façon impossible à distinguer d'un humain. Quel critère cela teste directement?",1,["Penser humainement","Agir humainement","Penser rationnellement","Agir rationnellement"],"Le jugement décrit porte sur les sorties observables, pas sur la mécanique interne.",["La réponse ne révèle pas directement un processus de pensée humain.","C'est la logique comportementale du test de Turing.","Aucune preuve n'est donnée sur la validité logique du raisonnement.","On ne sait pas si les actions optimisent un objectif."],"Test de Turing","easy",23],
        ["Chez Wang, une approche met l'accent sur la fonction ou la correspondance entrée-sortie, sans exiger les mêmes entrées et sorties concrètes que chez l'humain. Laquelle?",2,["Structure-IA","Comportement-IA","Fonction-IA","Principe-IA"],"Repère ce qui est comparé : structure interne, comportement observable, fonction abstraite ou principe général.",["La perspective structure porte sur des états ou changements comparables au cerveau.","La perspective comportementale juge les sorties externes ressemblant à celles d'un humain.","La perspective fonctionnelle compare les fonctions ou correspondances entrée-sortie.","La perspective principe porte sur un principe général, par exemple la rationalité."],"Définitions de l'IA selon Wang","hard",35],
        ["Un agent choisit à chaque étape l'action qui sert le mieux son objectif, compte tenu de l'information et des contraintes disponibles. Quelle perspective cela illustre?",3,["Penser humainement","Agir humainement","Penser rationnellement","Agir rationnellement"],"Demande-toi si le critère porte sur une ressemblance humaine ou sur le but à atteindre.",["Aucune comparaison aux pensées humaines n'est indiquée.","Aucune imitation du comportement humain n'est requise.","L'accent est mis sur l'action plutôt que sur les règles de pensée.","L'action est évaluée selon l'objectif et les contraintes."],"Rationalité","medium",24],
        ["Pourquoi définir l'IA est-il délicat selon le cours?",1,["Parce que l'IA ne possède aucune application pratique.","Parce que les critères dépendent de ce qu'on entend par intelligence et qu'il n'existe pas de consensus unique.","Parce que seules les machines conscientes peuvent être étudiées.","Parce que l'IA ne comprend qu'une seule méthode."],"Relie la difficulté à l'absence de définition consensuelle de l'intelligence.",["Le cours reconnaît de nombreux domaines pratiques.","Cette réponse reprend le problème de définition.","La conscience apparaît comme une question ouverte, non un prérequis de définition.","La présentation couvre plusieurs approches."],"Définir l'IA","medium",21],
        ["Quel exemple est le meilleur contre-exemple à l'affirmation « une performance surhumaine dans un domaine prouve l'AGI »?",0,["Un programme d'échecs dépasse des joueurs humains mais ne fait pas diverses autres tâches cognitives.","Un système accomplit plusieurs tâches cognitives variées avec compétence humaine.","Un réseau ajuste ses paramètres pendant l'entraînement.","Un programme utilise des règles logiques."],"La différence importante est la largeur des capacités transférables.",["Une réussite étroite ne démontre pas une compétence générale.","Cette description se rapproche davantage d'une compétence générale.","L'entraînement ne suffit pas à définir la portée générale.","Une représentation symbolique n'indique pas à elle seule l'étendue des capacités."],"IA spécialisée et AGI","medium",28]
      ]
    },
    chapitre2: {
      title: "Introduction à l'apprentissage automatique",
      tf: [
        ["En apprentissage supervisé, chaque exemple d'entraînement est associé à une cible ou étiquette.",true,"Compare la rétroaction disponible avec le non supervisé.","Le signal supervisé comprend une cible pour chaque exemple d'entraînement.","Apprentissage supervisé","easy",6],
        ["En apprentissage non supervisé, les exemples d'entraînement sont fournis sans étiquette cible.",true,"Le regroupement cherche une structure dans les données sans cible fournie.","L'absence de cibles distingue ici l'apprentissage non supervisé.","Apprentissage non supervisé","easy",7],
        ["En apprentissage par renforcement, la rétroaction prend typiquement la forme de récompenses ou de retours liés aux actions.",true,"La rétroaction n'est pas nécessairement une étiquette de classe immédiate.","L'agent apprend à partir des actions et de la rétroaction de l'environnement.","Apprentissage par renforcement","medium",9],
        ["Dans un problème supervisé, une colonne utilisée pour calculer la prédiction est une cible.",false,"La cible est ce que le modèle cherche à prédire; les colonnes d'entrée sont les attributs.","Les colonnes d'entrée sont les attributs; la cible est la réponse à prédire.","Attributs et cibles","easy",13],
        ["Prédire le prix d'une maison, une quantité numérique, est une tâche de classification.",false,"Regarde si la sortie est une catégorie ou une quantité.","Une quantité réelle correspond à la régression; la classification prédit des catégories.","Classification et régression","easy",17],
        ["Attribuer à une photo une étiquette parmi plusieurs espèces est une tâche de classification.",true,"La sortie appartient à une classe discrète.","Une étiquette de classe, même parmi plusieurs, relève de la classification.","Classification","easy",17],
        ["L'entraînement et l'inférence désignent le même calcul et la même étape du cycle du modèle.",false,"L'un ajuste le modèle; l'autre utilise un modèle déjà ajusté.","L'entraînement ajuste les paramètres; l'inférence applique le modèle pour produire des prédictions.","Entraînement et inférence","easy",11],
        ["Une grande exactitude mesurée sur les mêmes exemples que ceux utilisés pour entraîner le modèle garantit une bonne performance sur de nouvelles données.",false,"Un modèle peut mémoriser ou surajuster les données d'entraînement.","La performance d'entraînement n'est pas une estimation indépendante de la généralisation; il faut évaluer sur des données distinctes.","Généralisation","medium",25],
        ["L'ensemble de test devrait influencer les choix de modèle pendant l'entraînement afin de produire une estimation finale honnête.",false,"L'ensemble de test doit rester à l'écart des décisions de modélisation.","Les décisions guidées par le test rendent son évaluation moins indépendante. Il sert à estimer une performance finale sur des exemples non utilisés.","Séparation entraînement-test","medium",27],
        ["Les notions d'exemple, d'attribut et de cible sont utiles pour décrire un jeu supervisé.",true,"Un exemple est une observation; les attributs décrivent ses entrées.","Chaque observation fournit des valeurs d'attributs et une cible à apprendre en supervisé.","Données supervisées","easy",16],
        ["Si un classificateur est entraîné sur des étiquettes, il est nécessairement évalué correctement en mesurant sa performance sur l'entraînement.",false,"L'entraînement ne répond pas à la question de prédiction sur des cas inédits.","La performance doit être estimée sur des données réservées qui n'ont pas servi à ajuster le modèle.","Évaluation","medium",25],
        ["Une partition stratifiée vise à préserver approximativement la proportion des classes dans les sous-ensembles.",true,"Elle ne transforme pas pour autant l'évaluation en entraînement.","Stratifier aide à conserver des proportions de classes semblables dans les partitions.","Partition stratifiée","medium",27],
        ["Les recommandations personnalisées qui s'améliorent avec les retours des utilisateurs peuvent illustrer l'apprentissage automatique.",true,"Les exemples concrets de la présentation relient l'adaptation aux données ou retours.","Les systèmes de recommandation sont un exemple de problèmes auxquels l'apprentissage peut s'appliquer.","Applications de l'AA","easy",4],
        ["La variable cible peut être numérique ou catégorielle selon la tâche supervisée.",true,"Associe la nature de la sortie au type de problème.","Les cibles numériques indiquent généralement une régression; les catégories une classification.","Type de cible","medium",17],
        ["Changer la valeur du générateur aléatoire d'une séparation peut changer les observations du jeu test et le score obtenu.",true,"La composition d'un échantillon influe sur une mesure empirique.","La présentation propose d'essayer différentes valeurs de random_state; le score peut varier avec les observations testées.","Variabilité de l'évaluation","medium",27]
      ],
      mc: [
        ["Un modèle reçoit des courriels déjà étiquetés « indésirable » ou « légitime » et apprend à les classer. Quel type d'apprentissage est décrit?",0,["Supervisé","Non supervisé","Par renforcement","Inférence sans apprentissage"],"Cherche si chaque exemple fournit déjà une réponse cible.",["Chaque courriel a une étiquette cible.","Le scénario fournit explicitement des étiquettes.","Aucune interaction avec récompenses n'est mentionnée.","Le système ajuste un modèle à partir d'exemples étiquetés."],"Apprentissage supervisé","easy",6],
        ["Un algorithme regroupe des observations similaires alors qu'aucune catégorie n'a été fournie. Quelle description convient?",1,["Classification supervisée","Apprentissage non supervisé","Régression supervisée","Inférence à partir d'étiquettes connues"],"Aucune cible n'est fournie au départ.",["La classification supervisée utilise normalement des étiquettes.","Le regroupement sans étiquettes est non supervisé.","La régression supervisée exige une cible numérique.","Aucune étiquette connue n'est mentionnée."],"Apprentissage non supervisé","easy",7],
        ["Un robot essaie une action et reçoit une récompense selon le résultat. Quel signal d'apprentissage est le plus directement décrit?",2,["Cible numérique fournie pour chaque exemple","Catégorie connue pour chaque observation","Récompense liée à l'action","Aucune rétroaction"],"Pense à la rétroaction issue de l'interaction avec l'environnement.",["Une cible par observation décrit du supervisé.","Une étiquette de classe par observation décrit du supervisé.","Récompenses après des actions sont typiques du renforcement.","Une récompense est bien une rétroaction."],"Apprentissage par renforcement","medium",9],
        ["Dans un tableau de maisons, les colonnes superficie et nombre de chambres servent à prédire le prix. Quel est le rôle du prix?",3,["Un attribut d'entrée","Un identifiant nécessairement","Une observation","La cible"],"C'est la valeur demandée en sortie par le modèle.",["Les attributs d'entrée comprennent ici superficie et chambres.","Aucune information ne dit que le prix sert d'identifiant.","Une ligne entière serait une observation.","Le prix est la quantité prédite."],"Attributs et cibles","easy",16],
        ["Quelle tâche est une régression?",1,["Déterminer si un message est du pourriel","Prédire la durée d'un trajet en minutes","Identifier l'espèce d'un manchot","Attribuer un document à une catégorie"],"La variable prédite est-elle une quantité numérique ou une classe?",["Cette sortie est une catégorie.","Une durée est une quantité numérique.","Une espèce est une catégorie.","L'attribution à une catégorie est de la classification."],"Classification et régression","easy",17],
        ["Un modèle est déjà entraîné. On lui présente un nouveau manchot et il prédit son espèce. Quelle étape est effectuée?",1,["Entraînement","Inférence","Validation croisée","Création de cible"],"Le modèle est déjà ajusté; l'action consiste à l'utiliser.",["L'entraînement ajuste les paramètres à partir de données.","Appliquer le modèle à une nouvelle entrée pour prédire, c'est l'inférence.","Aucune répétition de plis n'est décrite.","Le modèle produit une prédiction, il ne crée pas l'étiquette de référence."],"Entraînement et inférence","easy",11],
        ["Un arbre prédit parfaitement les exemples qui ont servi à l'entraîner. Quelle conclusion est valide?",2,["Il généralisera nécessairement parfaitement.","Un ensemble de test est inutile.","Il faut une évaluation sur des exemples distincts pour estimer sa performance sur des données inédites.","Le modèle ne s'est pas entraîné."],"Une performance sur les données vues ne mesure pas directement les données jamais vues.",["Le surajustement reste possible.","Les données test fournissent une estimation utile.","Une partition distincte est nécessaire pour évaluer la généralisation.","Une prédiction parfaite d'entraînement est compatible avec l'ajustement."],"Généralisation","medium",25],
        ["Pourquoi réserver un ensemble de test avant de comparer plusieurs modèles?",0,["Pour garder une estimation finale basée sur des exemples n'ayant pas guidé les décisions de modélisation.","Pour augmenter artificiellement la taille des données d'entraînement.","Pour permettre au modèle d'apprendre les étiquettes test.","Pour garantir un score identique à chaque partition."],"Le test sert à une évaluation finale indépendante.",["C'est la raison méthodologique de la séparation.","Un jeu de test est réservé et n'augmente pas l'entraînement.","L'apprentissage des étiquettes test compromet l'évaluation.","Les scores peuvent varier selon les exemples."],"Séparation entraînement-test","medium",27],
        ["À quoi sert principalement stratify=y lors d'une séparation supervisée?",3,["À sélectionner les meilleurs attributs","À calculer la prédiction","À entraîner deux modèles distincts","À préserver approximativement la proportion des classes"],"L'option concerne la composition relative des partitions.",["La stratification n'effectue pas de sélection d'attributs.","Elle ne prédit rien.","Elle répartit les données, sans entraîner à elle seule deux modèles.","Elle conserve des proportions de classes approximativement semblables."],"Partition stratifiée","medium",27],
        ["Quelle description distingue correctement classification et régression?",2,["Classification prédit une quantité; régression prédit une catégorie.","Les deux prédisent toujours une étiquette textuelle.","Classification prédit une classe; régression prédit typiquement une valeur numérique.","La différence dépend seulement du nombre d'exemples."],"Regarde le type de valeur cible.",["Les rôles sont inversés.","Une régression peut produire une quantité numérique.","C'est la distinction attendue.","Le type de tâche vient de la cible, non du volume d'exemples."],"Classification et régression","easy",17]
      ]
    },
    chapitre3: {
      title: "Algorithmes d'apprentissage",
      tf: [
        ["Un arbre de décision choisit des divisions successives à partir de conditions sur les attributs.",true,"Chaque nœud interne pose une condition qui sépare les exemples.","Les arbres organisent les décisions en tests successifs sur les attributs.","Arbres de décision","easy",8],
        ["Une division d'arbre de décision doit nécessairement créer des régions de décision linéaires dans l'espace complet.",false,"Plusieurs divisions axis-aligned peuvent former une frontière globale non linéaire.","Chaque division simple peut être une coupure par seuil; leur combinaison peut créer une frontière non linéaire.","Frontières d'arbres","medium",21],
        ["Un arbre de décision construit par choix glouton garantit toujours l'arbre globalement optimal.",false,"Glouton signifie choisir localement, sans examiner toutes les suites futures.","Le choix glouton optimise la division courante selon un critère; il ne garantit pas la meilleure structure globale.","Apprentissage glouton","hard",12],
        ["L'entropie sert à mesurer l'impureté d'un nœud dans l'exemple d'arbre du cours.",true,"Un nœud pur possède des exemples d'une seule classe.","L'entropie plus faible correspond à des étiquettes plus homogènes; elle peut aider à évaluer une division.","Entropie et impureté","medium",10],
        ["Une division utile peut être évaluée à partir de l'impureté pondérée de ses enfants.",true,"Les groupes enfants n'ont pas forcément la même taille.","Le poids tient compte de la taille relative des partitions créées par la division.","Choix de division","medium",11],
        ["La profondeur maximale d'un arbre peut servir de condition d'arrêt ou de contrôle de complexité.",true,"Une limite de profondeur contraint le nombre de décisions successives.","max_depth limite la profondeur et peut empêcher une croissance excessive de l'arbre.","Hyperparamètres d'arbre","easy",15],
        ["KNN construit nécessairement un ensemble compact de règles avant de pouvoir prédire.",false,"KNN conserve les observations d'entraînement et les consulte pour une nouvelle prédiction.","KNN est décrit comme apprenant paresseusement : il mémorise les observations et cherche les voisins au moment de la prédiction.","KNN","easy",30],
        ["Dans la classification KNN, les étiquettes des voisins contribuent à un vote pour choisir la classe.",true,"La prédiction dépend du voisinage retenu.","Le classificateur compare les voisins puis agrège leurs étiquettes, uniformément ou avec des poids.","Vote KNN","easy",30],
        ["Avec des poids de distance, les voisins éloignés ont davantage d'influence sur la prédiction que les voisins proches.",false,"La pondération cherche à renforcer l'influence locale.","Une pondération par la distance augmente l'influence des observations proches.","Pondération KNN","medium",36],
        ["Les échelles des attributs peuvent changer les distances utilisées par KNN.",true,"Une différence de grande amplitude peut dominer une distance.","Les distances sont sensibles à l'échelle; le prétraitement est souvent important pour KNN.","Échelle et distance","medium",36],
        ["Un très grand nombre de voisins peut lisser des structures locales utiles dans KNN.",true,"La taille du voisinage contrôle la quantité de contexte utilisée.","Un grand k peut masquer des motifs locaux, tandis qu'un petit k est plus sensible au bruit.","Choix de k","medium",36],
        ["Le choix de k dans KNN contrôle le nombre de voisins consultés pour une prédiction.",true,"k détermine la taille du voisinage qui participe au vote.","Un petit k rend les prédictions plus locales; un grand k lisse davantage les structures observées.","Hyperparamètre k de KNN","easy",30],
        ["En régression KNN, la prédiction est généralement fondée sur les valeurs cibles du voisinage.",true,"La tâche prédit une quantité plutôt qu'une classe.","KNN peut agréger les cibles numériques des voisins, souvent par une moyenne.","KNN en régression","medium",36],
        ["Ajouter des attributs sans ajuster leur échelle ne peut jamais modifier le classement des voisins.",false,"Une distance combine les différences numériques entre plusieurs attributs.","Les attributs aux amplitudes élevées peuvent dominer la distance et modifier les voisins les plus proches.","Distance KNN","hard",36],
        ["Des frontières d'arbre et de KNN peuvent être différentes même lorsqu'ils sont entraînés sur le même jeu de données.",true,"Les algorithmes induisent des règles de décision différentes.","Les exemples du cours illustrent que différents algorithmes produisent différentes frontières de décision.","Comparer les modèles","medium",37]
      ],
      mc: [
        ["Un arbre classe une observation en suivant les conditions des nœuds jusqu'à une feuille. Que représente le chemin suivi?",1,["Un tirage aléatoire de poids","Une suite de tests sur les attributs","Une moyenne de distances","Une validation croisée"],"Les nœuds internes découpent l'espace selon des conditions.",["Les arbres n'échantillonnent pas nécessairement de poids.","Chaque branche correspond aux résultats de tests successifs.","La distance est centrale pour KNN, pas le parcours d'arbre.","La validation croisée est une procédure d'évaluation."],"Arbres de décision","easy",8],
        ["Un nœud parent contient deux classes en proportions égales. Une division crée un grand enfant presque pur et un très petit enfant mixte. Que faut-il examiner pour juger la division?",2,["Seulement l'impureté du petit enfant","Seulement le nombre total d'attributs","L'impureté des enfants en tenant compte de leur taille relative","L'identifiant de la ligne"],"Le cours décrit une impureté agrégée pondérée.",["Ignorer le grand enfant ne mesure pas la qualité globale.","Le nombre d'attributs n'est pas le critère de cette division.","La pondération tient compte du nombre d'exemples dans chaque enfant.","Les identifiants ne mesurent pas l'impureté."],"Entropie et impureté","hard",10],
        ["Pourquoi un arbre très profond peut-il mémoriser le jeu d'entraînement sans bien généraliser?",0,["Il peut créer des divisions très spécifiques qui capturent aussi le bruit.","La profondeur empêche toute décision conditionnelle.","Un arbre profond devient un classificateur KNN.","Il ne peut pas utiliser les attributs."],"Relie la complexité de l'arbre à l'adaptation aux exemples observés.",["Une structure complexe peut s'ajuster aux détails non généralisables.","La profondeur permet davantage de décisions, pas aucune.","Changer d'algorithme ne résulte pas de la profondeur.","Les divisions d'un arbre utilisent des attributs."],"Complexité et généralisation","medium",15],
        ["Quel résultat peut-on obtenir en modifiant la profondeur maximale d'un arbre?",3,["Changer les étiquettes réelles","Transformer une tâche de classification en apprentissage non supervisé","Forcer toutes les feuilles à contenir une seule classe","Contrôler la complexité permise de l'arbre"],"max_depth est un réglage structurel du modèle.",["Le paramètre ne modifie pas la vérité terrain.","Il ne change pas la présence d'étiquettes.","La profondeur ne garantit pas des feuilles parfaitement pures.","La profondeur limite la taille de l'arbre."],"Hyperparamètres d'arbre","easy",15],
        ["Dans KNN, que doit faire le modèle pour classer un nouvel exemple?",1,["Appliquer uniquement une règle apprise lors d'une étape paramétrique","Rechercher les exemples proches et agréger leurs étiquettes","Calculer l'entropie de toute l'arborescence","Rejouer l'entraînement sur des données non étiquetées"],"KNN reporte une partie du travail au moment de la prédiction.",["KNN n'est pas principalement une liste de paramètres de séparation apprise.","Le voisinage détermine le vote de classe.","L'entropie peut caractériser une division d'arbre.","Le scénario ne décrit pas un nouvel entraînement."],"KNN","easy",30],
        ["Avec k=1, une observation test isolée est très proche d'un exemple d'entraînement bruité. Quel risque est plausible?",2,["Le vote devient forcément majoritaire sur tout le jeu","Les attributs perdent leurs unités","Le bruit de cet unique voisin peut déterminer la classe","KNN n'a plus besoin de données"],"Un très petit voisinage dépend fortement des observations locales.",["k=1 ne compte qu'un voisin.","Le risque concerne le choix de voisin, pas les unités.","Un voisin bruité peut fortement influencer la prédiction.","KNN conserve les données pour prédire."],"Choix de k","medium",36],
        ["Pourquoi standardiser les attributs peut-il être utile avant KNN?",0,["Pour éviter qu'une variable de grande amplitude domine artificiellement les distances.","Pour transformer toutes les cibles en classes.","Pour retirer le besoin de choisir k.","Pour garantir zéro erreur de test."],"Pense à la façon dont une distance combine des différences numériques.",["Une échelle comparable limite la domination d'un attribut.","La mise à l'échelle ne transforme pas les cibles.","k reste nécessaire.","Aucun prétraitement ne garantit zéro erreur."],"Échelle et distance","medium",36],
        ["Un étudiant dit : « KNN est coûteux seulement pendant l'entraînement ». Quelle correction est la meilleure?",1,["KNN ne stocke jamais les observations.","La recherche et le vote sur les voisins ont lieu lors de la prédiction.","La prédiction ne dépend pas des données d'entraînement.","KNN est toujours plus rapide que les arbres."],"La présentation qualifie KNN d'apprentissage paresseux.",["Il conserve les exemples d'entraînement.","La prédiction doit rechercher dans les observations mémorisées.","Les distances sont calculées par rapport aux observations d'entraînement.","Le coût relatif dépend des données et des réglages."],"Coût de KNN","medium",36],
        ["Quelles sont les régions de décision d'un arbre construit avec des seuils sur deux attributs?",3,["Des cercles nécessairement concentriques","Une seule droite toujours diagonale","Des régions probabilistes sans frontières","Des régions rectangulaires dont la combinaison peut former une frontière globale non linéaire"],"Chaque test par seuil est aligné sur un axe dans l'illustration.",["Le cours ne décrit pas des cercles.","Un seuil sur un attribut forme une séparation verticale ou horizontale.","Les décisions créent des classes déterminées par des régions.","Combiner plusieurs tests peut produire une frontière complexe."],"Frontières d'arbres","hard",21],
        ["Dans un espace de grande dimension, pourquoi les voisins les plus proches peuvent-ils devenir moins informatifs pour KNN?",1,["Les distances n'existent plus","La plupart des observations deviennent également éloignées et le contraste utile entre distances diminue","KNN ne peut plus mémoriser les exemples","Les cibles deviennent nécessairement continues"],"Pense à la perte de contraste entre les distances dans beaucoup de dimensions.",["Une distance peut toujours être calculée.","C'est l'intuition de la malédiction de la dimensionnalité mentionnée dans le cours.","Le classificateur conserve toujours les exemples.","La dimension n'impose pas un type de cible."],"Malédiction de la dimensionnalité","hard",36]
      ]
    },
    chapitre4: {
      title: "Régression linéaire et descente de gradient",
      tf: [
        ["La régression est supervisée lorsque les exemples fournissent une cible numérique à prédire.",true,"Ici la sortie est une quantité réelle.","La cible numérique caractérise la régression supervisée.","Régression","easy",4],
        ["Une hypothèse linéaire combine les attributs à l'aide de paramètres et d'un terme de biais.",true,"Les coefficients déterminent la contribution linéaire des attributs.","La fonction de prédiction linéaire est paramétrée par des coefficients et généralement un intercept.","Hypothèse linéaire","easy",6],
        ["L'erreur quadratique moyenne pénalise les erreurs par leur valeur absolue.",false,"La perte au carré élève l'erreur au carré.","L'EQM moyenne les carrés des écarts prédiction-cible, pas leurs valeurs absolues.","Erreur quadratique moyenne","easy",8],
        ["Minimiser l'EQM revient à rechercher les paramètres qui réduisent les résidus au carré sur les données considérées.",true,"Un résidu est l'écart entre une prédiction et sa cible.","La fonction de coût mesure l'erreur entre prédictions et cibles.","Objectif de régression","medium",8],
        ["L'espace des paramètres et l'espace des entrées décrivent la même chose.",false,"L'un contient des valeurs de coefficients; l'autre contient les exemples et attributs.","Les paramètres sont les valeurs apprises du modèle; les entrées sont les observations sur lesquelles il prédit.","Espaces des paramètres et des données","medium",10],
        ["La descente de gradient met à jour les paramètres dans la direction opposée au gradient de la perte.",true,"Le gradient pointe vers l'augmentation locale la plus rapide.","Soustraire un pas de gradient vise une diminution locale de l'objectif.","Descente de gradient","easy",22],
        ["Si le taux d'apprentissage est exactement nul, les paramètres ne changent pas lors des mises à jour de gradient.",true,"Le taux multiplie la correction calculée.","Avec un pas nul, aucune mise à jour n'est appliquée.","Taux d'apprentissage","easy",23],
        ["Un taux d'apprentissage arbitrairement grand garantit une convergence plus rapide vers le minimum.",false,"Un pas trop grand peut dépasser le minimum ou diverger.","La taille du pas doit être adaptée; une valeur trop grande peut rendre l'optimisation instable.","Taux d'apprentissage","medium",23],
        ["Le signe de la dérivée indique dans quel sens la fonction augmente ou diminue localement.",true,"La dérivée décrit la pente à un point.","Une dérivée positive signifie que la fonction augmente localement quand l'entrée augmente; une négative indique le contraire.","Dérivée","medium",19],
        ["Un gradient nul à un point prouve toujours qu'on a trouvé le minimum global.",false,"Un point stationnaire peut aussi être un maximum ou un point selle.","Le gradient nul indique un point stationnaire; seul, il ne garantit pas un minimum global.","Points stationnaires","hard",22],
        ["La dérivée partielle mesure le changement de la fonction quand un paramètre varie, en tenant les autres fixes.",true,"C'est la version multivariable de la pente selon une coordonnée.","Une dérivée partielle quantifie le changement selon un paramètre particulier.","Dérivées partielles","medium",24],
        ["La descente de gradient par lot calcule chaque mise à jour à partir de tous les exemples d'entraînement.",true,"Le nom batch se rapporte à la taille de l'ensemble contribuant à une mise à jour.","La mise à jour par lot utilise l'ensemble d'entraînement complet.","Gradient par lot","easy",33],
        ["Une mise à jour stochastique utilisant un seul exemple est généralement plus coûteuse par mise à jour que le calcul par lot complet.",false,"Le coût par mise à jour est plus faible pour un seul exemple, mais les mises à jour sont plus bruyantes.","Une mise à jour stochastique est légère, mais sa direction varie davantage.","Gradient stochastique","medium",34],
        ["Une descente de gradient peut être évaluée en suivant l'évolution de la perte pendant les mises à jour.",true,"L'objectif d'optimisation fournit une quantité observable à suivre.","La diminution de la perte indique si l'optimisation progresse, même si elle ne garantit pas à elle seule la généralisation.","Suivi de l'optimisation","medium",31],
        ["La normalisation ou l'échelle des entrées peut influencer le comportement de l'optimisation numérique.",true,"L'échelle affecte les pentes et la forme des contours de perte.","Les échelles des paramètres/attributs influencent les pas nécessaires et la convergence pratique.","Géométrie de l'optimisation","hard",28]
      ],
      mc: [
        ["Un modèle prédit un nombre de minutes avant l'arrivée d'un bus. Quel type de tâche correspond à la cible?",1,["Classification","Régression","Regroupement non supervisé","Décision sans données"],"La cible est un nombre mesurable.",["Les catégories discrètes correspondent à la classification.","Une durée numérique est une cible de régression.","Aucune absence d'étiquettes n'est indiquée.","Un modèle est explicitement utilisé."],"Régression","easy",4],
        ["Un modèle linéaire a une prédiction trop faible pour un exemple. Quel est son résidu si résidu = prédiction − cible?",3,["La prédiction seule","La cible seule","La somme des attributs","Un nombre négatif"],"Soustrais une valeur cible plus grande de la prédiction plus petite.",["Il faut comparer les deux valeurs.","Le résidu est une différence, pas la cible.","Les attributs ne remplacent pas la définition du résidu.","Prédiction moins cible est négatif lorsque la prédiction est inférieure."],"Résidus","easy",8],
        ["Quel changement de paramètre correspond à un pas de descente de gradient de taille η?",0,["θ ← θ − η∇J(θ)","θ ← θ + η∇J(θ)","θ ← J(θ) − η","θ ← θ/∇J(θ)"],"Le gradient pointe localement vers la hausse de l'objectif.",["Soustraire le gradient vise la diminution de la perte.","Ajouter le gradient suit la hausse locale.","La perte n'est pas le vecteur de paramètres.","La règle ne divise pas les paramètres par le gradient."],"Descente de gradient","easy",22],
        ["À une étape, le gradient est positif pour un paramètre θ et η>0. Que fait la règle de descente pour θ?",2,["Augmente nécessairement θ","Laisse θ inchangé","Diminue θ","Remplace θ par zéro"],"Applique la soustraction de η fois un nombre positif.",["Le signe du gradient rend le pas négatif.","Cela ne serait vrai qu'avec gradient ou taux nul.","θ ← θ − ηg diminue lorsque g>0.","La formule n'impose pas zéro."],"Mise à jour d'un paramètre","medium",23],
        ["Quel est le risque d'un taux d'apprentissage trop élevé?",1,["Aucun paramètre ne sera jamais mis à jour","Les mises à jour peuvent dépasser les bonnes valeurs et osciller ou diverger","L'EQM devient automatiquement une erreur absolue","Le jeu de données perd ses étiquettes"],"Le pas représente l'amplitude de chaque changement.",["Un taux non nul produit des mises à jour si le gradient ne l'est pas.","De grands pas peuvent franchir le minimum et déstabiliser l'apprentissage.","Le choix de perte ne change pas ainsi.","Le taux ne retire pas les étiquettes."],"Taux d'apprentissage","medium",23],
        ["Quelle phrase décrit correctement une dérivée partielle ∂J/∂θ₁?",0,["Variation locale de J selon θ₁, les autres paramètres étant fixes","Valeur de J lorsque tous les paramètres valent un","Erreur moyenne sur l'ensemble test","Prédiction de la cible pour θ₁"],"Elle isole l'effet d'une coordonnée des paramètres.",["C'est l'interprétation de la dérivée partielle.","Ce n'est pas une évaluation à une affectation particulière.","Elle n'est pas la perte test entière.","Un paramètre n'est pas une entrée à prédire."],"Dérivées partielles","medium",24],
        ["Si on calcule la mise à jour sur tout l'ensemble d'entraînement avant de modifier les paramètres, de quel type s'agit-il?",3,["Test final","Mise à jour d'inférence","Descente en coordonnées obligatoirement","Descente de gradient par lot"],"Le lot contient ici tous les exemples.",["L'entraînement optimise le modèle.","L'inférence n'ajuste pas les paramètres.","Aucun changement de coordonnée séquentielle n'est précisé.","Utiliser tous les exemples pour une mise à jour définit la version par lot."],"Gradient par lot","easy",33],
        ["Pourquoi les mises à jour stochastiques peuvent-elles sembler plus irrégulières?",2,["Elles utilisent toujours le test","Elles n'ont aucun gradient","Chaque mise à jour utilise une estimation issue d'un exemple ou d'un mini-lot plutôt que toute la population d'entraînement","Elles minimisent une autre tâche"],"Le calcul de chaque pas utilise moins d'exemples.",["Le test reste réservé à l'évaluation.","Une estimation de gradient est calculée.","Moins d'exemples produisent des mises à jour plus bruyantes.","Le type de tâche n'est pas changé."],"Gradient stochastique","medium",34],
        ["Au voisinage d'un point, la dérivée de f est négative. Quelle affirmation est la plus juste?",1,["f augmente si x augmente légèrement","f diminue si x augmente légèrement","f est nécessairement nulle partout","f atteint nécessairement son minimum global"],"Le signe de la pente indique la variation locale.",["Une dérivée négative indique une pente descendante quand x augmente.","C'est l'interprétation locale du signe négatif.","La pente à un point ne décrit pas partout la fonction.","Une pente négative n'établit pas un minimum."],"Interpréter une dérivée","medium",20],
        ["Pourquoi minimiser l'EQM peut favoriser les grands résidus davantage que la perte absolue?",2,["L'EQM ignore les erreurs","L'EQM transforme les erreurs en catégories","Le carré amplifie la contribution des écarts de grande magnitude","La valeur absolue est toujours plus grande que le carré"],"Compare 1² et 3² avec leurs magnitudes.",["L'EQM est construite à partir des écarts.","Elle reste une perte numérique.","Les grandes erreurs contribuent quadratiquement.","Cette relation dépend de la magnitude et ne soutient pas cette généralité."],"Erreur quadratique moyenne","medium",8]
      ]
    },
    chapitre5: {
      title: "Régression logistique",
      tf: [
        ["La régression logistique est utilisée pour des tâches de classification, même si son nom contient « régression ». ",true,"Regarde le type de sortie final du modèle.","Elle transforme un score en probabilité puis produit une classe selon un seuil.","Régression logistique","easy",4],
        ["La fonction sigmoïde transforme un score réel en une valeur comprise entre 0 et 1.",true,"Ses sorties s'interprètent comme scores probabilistes.","La sigmoïde borne le score dans l'intervalle ouvert (0,1), ce qui permet une interprétation probabiliste.","Sigmoïde","easy",8],
        ["Une probabilité prédite de 0,8 signifie que la classe prédite doit toujours être la classe négative.",false,"La décision dépend du seuil choisi et de quelle classe est considérée positive.","Avec un seuil habituel de 0,5, 0,8 dépasse le seuil et mène à la classe positive; d'autres seuils sont possibles.","Seuil","medium",9],
        ["Modifier le seuil de décision peut changer les étiquettes prédites sans réentraîner les coefficients.",true,"Le seuil intervient après le calcul des probabilités.","Les scores/probabilités restent les mêmes; le seuil change la règle de conversion en classe.","Seuil","easy",9],
        ["Dans une classification binaire, les classes peuvent être codées par deux valeurs distinctes, dont 0 et 1.",true,"La codification sert à distinguer les deux catégories.","La régression logistique binaire modélise la probabilité associée à une classe codée, souvent 0/1.","Classification binaire","easy",6],
        ["La stratégie un-contre-tous entraîne un seul classificateur binaire pour toutes les classes et sans comparaison de scores.",false,"Chaque classe peut être comparée aux autres à l'aide d'un classificateur binaire.","Un classificateur par classe oppose cette classe à toutes les autres; les scores permettent ensuite de choisir.","Un contre tous","medium",18],
        ["Un classificateur multi-étiquette peut attribuer plusieurs étiquettes à une même observation.",true,"Plusieurs étiquettes peuvent coexister pour le même exemple.","Le multi-étiquette se distingue du multiclasse exclusif, où une seule classe est assignée.","Types de classification","medium",5],
        ["Les coefficients d'un classificateur logistique affectent le score linéaire calculé à partir des attributs.",true,"Le score est une combinaison des valeurs d'entrée et des coefficients.","Les coefficients pondèrent les attributs dans le score avant la sigmoïde.","Coefficients","easy",24],
        ["Un coefficient positif signifie toujours que la probabilité augmente indépendamment des autres attributs et de leur codage.",false,"Le coefficient agit sur un score; l'interprétation dépend du codage et des autres valeurs.","Un coefficient positif augmente le score linéaire lorsque l'attribut augmente, toutes choses égales; l'effet probabiliste varie avec la position sur la sigmoïde.","Interprétation des coefficients","hard",24],
        ["Appliquer une transformation ajustée sur l'entraînement au jeu test devrait employer les statistiques mémorisées plutôt que réajuster la transformation sur le test.",true,"Le test doit rester indépendant.","Le prétraitement s'ajuste sur l'entraînement et transform() applique ces paramètres au test.","Prétraitement et test","medium",25],
        ["Dans un problème binaire linéaire, le score nul correspond à une probabilité de 0,5 avec la sigmoïde standard.",true,"La sigmoïde est symétrique autour du score zéro.","σ(0)=0,5; sous seuil 0,5, la frontière de décision est le lieu où le score linéaire est nul.","Frontière de décision","medium",10],
        ["Les termes multiclasse et multi-étiquette signifient tous deux qu'une observation doit recevoir plusieurs classes simultanément.",false,"L'un autorise plusieurs étiquettes; l'autre choisit une classe parmi plusieurs.","En multiclasse exclusif, une seule classe est choisie; en multi-étiquette, plusieurs étiquettes peuvent coexister.","Types de classification","medium",5],
        ["L'ajustement des coefficients et le choix du seuil de classification sont deux opérations conceptuellement distinctes.",true,"L'un construit le modèle; l'autre convertit une probabilité en décision.","Le seuil peut être changé après l'ajustement du modèle pour modifier le compromis de décision.","Modèle et règle de décision","medium",9],
        ["Une régression logistique entraînée sur un jeu de données étiqueté peut être évaluée sur les mêmes données sans risque de biais optimiste.",false,"Le modèle a déjà vu ces exemples pendant l'ajustement.","Une évaluation sur les données d'entraînement peut surestimer la généralisation; garder un test séparé est important.","Évaluation","medium",22],
        ["La décision un-contre-tous permet de réutiliser un classificateur binaire dans un problème à plusieurs classes.",true,"Une cible à plusieurs classes peut être décomposée en comparaisons binaires.","On entraîne une sortie binaire par classe contre le reste, puis on compare les scores.","Un contre tous","medium",18]
      ],
      mc: [
        ["Un classificateur calcule le score s=−1, puis lui applique la sigmoïde. Qu'est-ce qui change directement?",0,["Le score est transformé en probabilité entre 0 et 1","La classe réelle de l'exemple","Les coefficients appris","Le nombre de catégories du jeu"],"La sigmoïde agit sur le score produit par le modèle.",["C'est sa fonction : associer un score à une probabilité.","La cible réelle est connue dans les données, elle ne change pas.","Les coefficients ne sont pas réentraînés par cette seule opération.","La sigmoïde seule n'ajoute pas de classes."],"Sigmoïde","easy",8],
        ["Le modèle prédit p=0,62 et le seuil est 0,70. Quelle classe prédit-il si p est la probabilité de la classe positive?",1,["Positive","Négative","Les deux étiquettes","Aucune prédiction possible"],"Compare p au seuil avant d'attribuer l'étiquette.",["La probabilité n'atteint pas le seuil positif.","0,62 est inférieur à 0,70.","Une classification binaire par seuil choisit une étiquette.","Le seuil et la probabilité suffisent pour prendre la décision."],"Seuil","easy",9],
        ["Un service veut attribuer séparément les catégories « facture », « contrat » et « reçu », et un document peut relever de deux catégories. Quel type de problème décrit-il?",3,["Binaire exclusif","Multiclasse exclusif","Régression","Multi-étiquette"],"Les étiquettes peuvent-elles coexister pour le même document?",["Plus de deux catégories sont disponibles.","Le multiclasse exclusif choisit une seule catégorie.","Les sorties sont des étiquettes, non une quantité.","Plusieurs étiquettes peuvent être vraies simultanément."],"Types de classification","medium",5],
        ["On souhaite classer des images en chat, chien ou oiseau à raison d'une seule espèce par image. Quelle description est la plus juste?",1,["Régression multivariée","Classification multiclasse","Classification multi-étiquette nécessairement","Apprentissage non supervisé"],"Il y a plusieurs classes possibles, mais une seule par image.",["La sortie n'est pas une quantité numérique.","Plus de deux catégories exclusives correspondent au multiclasse.","Le scénario impose une classe unique.","Les étiquettes d'espèce peuvent servir de cibles supervisées."],"Types de classification","easy",5],
        ["Comment la stratégie un-contre-tous traite-t-elle trois classes?",0,["Elle entraîne un classificateur par classe, opposant cette classe aux autres.","Elle fusionne toutes les classes dans une cible numérique continue.","Elle élimine le besoin de données étiquetées.","Elle utilise un seul seuil commun sans modèle binaire."],"Transforme le problème en plusieurs problèmes binaires.",["C'est le principe de l'approche one-vs-rest.","Les classes restent des catégories.","Les modèles sont entraînés avec les étiquettes.","Chaque classe obtient un classificateur/score à comparer."],"Un contre tous","medium",18],
        ["Pour un score linéaire s=0, quelle valeur donne la sigmoïde standard?",2,["0","1","0,5","−0,5"],"La sigmoïde est symétrique au point central.",["À l'infini négatif, elle tend vers 0.","À l'infini positif, elle tend vers 1.","σ(0)=1/(1+1)=0,5.","La sortie ne devient pas négative."],"Sigmoïde","easy",8],
        ["Un analyste baisse le seuil de 0,5 à 0,3 sans réentraîner le modèle. Quel effet est plausible?",3,["Les poids du réseau sont remplacés","Les probabilités deviennent toutes égales","Les étiquettes réelles changent","Davantage d'exemples peuvent être prédits positifs"],"Une probabilité doit maintenant franchir une barre plus basse.",["Un seuil ne réajuste pas les paramètres.","Les probabilités calculées ne sont pas recalculées du fait du seuil.","Les étiquettes terrain ne changent pas.","Des valeurs entre 0,3 et 0,5 deviennent désormais positives."],"Seuil","medium",9],
        ["Un score linéaire dépend de plusieurs attributs. Que représente typiquement un coefficient positif?",1,["L'attribut est sans effet dans tous les cas","À attributs et codage fixés, augmenter cet attribut augmente le score linéaire","La probabilité augmente d'une quantité constante dans toutes les situations","La classe cible devient positive automatiquement"],"Interprète d'abord l'effet sur le score, avant la sigmoïde.",["Un coefficient nul serait sans effet linéaire direct.","C'est l'effet direct du signe du coefficient sur le score, toutes choses égales.","La sigmoïde rend la variation de probabilité dépendante du score actuel.","La décision dépend également du seuil."],"Interprétation des coefficients","hard",24],
        ["On veut comparer chaque espèce d'oiseau à toutes les autres. Quelle stratégie de classification binaire est adaptée?",2,["Ajuster un seul modèle sans étiquettes","Remplacer les classes par leurs noms alphabétiques","Un contre tous","Moyenner les attributs"],"La décomposition crée une tâche positive contre le reste pour chaque classe.",["Le besoin de classes reste supervisé.","Le classement alphabétique n'est pas un modèle.","One-vs-rest étend un classificateur binaire aux classes multiples.","Les moyennes d'attributs ne définissent pas la méthode."],"Un contre tous","medium",18],
        ["Pourquoi une transformation telle qu'un scaler doit-elle être ajustée avant sur l'entraînement seulement?",0,["Pour empêcher les informations du test d'influencer le prétraitement et l'évaluation finale","Pour augmenter le nombre de classes","Pour convertir les probabilités en scores","Pour apprendre les étiquettes du test"],"Le test sert à estimer une performance indépendante.",["L'ajustement sur le test créerait une fuite d'information.","La mise à l'échelle ne crée pas de catégories.","Le scaler transforme les entrées, pas les probabilités en score.","Les cibles du test ne sont pas utilisées pour entraîner."],"Fuite de données","medium",25]
      ]
    },
    chapitre6: {
      title: "Entropie croisée et géométrie logistique",
      tf: [
        ["L'entropie croisée binaire peut être reliée à la vraisemblance d'une cible de Bernoulli.",true,"La cible binaire peut être modélisée avec une variable de Bernoulli.","Minimiser la log-vraisemblance négative donne la perte d'entropie croisée binaire.","Entropie croisée","medium",8],
        ["L'erreur quadratique moyenne est toujours préférable à l'entropie croisée pour entraîner une régression logistique.",false,"La saturation de la sigmoïde peut rendre le gradient MSE peu informatif lorsqu'une prédiction est très confiante et fausse.","La présentation compare les gradients et explique pourquoi la perte logistique offre une correction plus utile dans ces cas.","Choix de perte","hard",11],
        ["Une frontière de décision logistique binaire correspond au niveau où le score linéaire atteint la valeur associée au seuil.",true,"Avec seuil 0,5 et sigmoïde standard, cette valeur de score est zéro.","Le seuil transforme un score/probabilité en classes; sa frontière est une équation linéaire dans les attributs.","Frontière de décision","medium",14],
        ["Le vecteur normal d'un hyperplan est parallèle à la frontière de décision.",false,"Il pointe perpendiculairement au plan.","Le vecteur des coefficients est normal à l'hyperplan; il est perpendiculaire à la frontière.","Géométrie linéaire","medium",15],
        ["Le score linéaire et la probabilité logistique sont deux grandeurs identiques.",false,"Une fonction non linéaire, la sigmoïde, relie les deux.","Le score est un réel non borné; la sigmoïde le transforme en probabilité entre 0 et 1.","Score et probabilité","easy",4],
        ["La distance signée à une frontière et le score linéaire peuvent différer d'un facteur lié à la norme des coefficients.",true,"Une forme linéaire peut être normalisée pour exprimer une distance géométrique.","Le score non normalisé ne mesure pas à lui seul une distance euclidienne; la norme des poids intervient.","Score et distance","hard",16],
        ["Deux observations à même distance signée de la frontière doivent nécessairement avoir la même classe réelle.",false,"La distance décrit la position relative au modèle, pas la vérité terrain.","La prédiction dépend du côté du seuil; les vraies étiquettes peuvent être mal classées de chaque côté.","Frontière et erreur","medium",16],
        ["Une observation classée négative sous le seuil se trouve du côté négatif de la frontière du modèle.",true,"La classe prédite est déterminée par le seuil, pas par une certitude.","La frontière sépare les régions où le modèle assigne les étiquettes prédites.","Décision logistique","easy",14],
        ["L'entropie croisée pénalise fortement une prédiction erronée faite avec une grande confiance.",true,"Regarde le logarithme de la probabilité attribuée à la vraie classe.","Une probabilité très faible pour l'étiquette vraie entraîne une perte logarithmique élevée.","Interpréter la perte","medium",9],
        ["Si la cible est y=1 et le modèle prédit p proche de 1, la perte binaire est faible.",true,"La prédiction attribue une forte probabilité à la classe vraie.","La perte −log(p) est proche de zéro lorsque p est proche de 1.","Perte binaire","easy",9],
        ["Si la cible est y=1 et p=0, la perte d'entropie croisée est faible parce que le modèle est certain.",false,"Le modèle est certain de la mauvaise classe dans ce cas.","Attribuer une probabilité quasi nulle à la classe vraie entraîne une très grande pénalité.","Confiance erronée","medium",9],
        ["La descente de gradient peut entraîner la régression logistique en mettant à jour les coefficients pour réduire l'objectif.",true,"Le modèle est paramétré et la perte différentiable.","Le gradient de la perte fournit une direction de mise à jour des paramètres.","Optimisation logistique","easy",18],
        ["Dans une classification linéaire, la frontière dans l'espace des attributs est définie par une équation linéaire.",true,"Le score avant sigmoïde est une combinaison linéaire des attributs.","Le seuil impose une constante au score linéaire, ce qui définit un hyperplan.","Frontière linéaire","medium",14],
        ["Une distance signée positive ou négative peut indiquer de quel côté de la frontière se trouve un point.",true,"Le signe indique le côté; l'amplitude la distance selon la convention de normalisation.","La distance signée encode le côté de la frontière et la proximité géométrique.","Distance signée","medium",16],
        ["L'entropie croisée et l'EQM produisent toujours le même gradient pour une sortie sigmoïde.",false,"Le cours compare précisément leurs dérivées.","Les pertes ont des gradients différents; la dérivée de la sigmoïde peut atténuer la correction de la MSE.","Gradient et perte","hard",11]
      ],
      mc: [
        ["Pour y=1, laquelle des probabilités prédites entraîne la plus grande entropie croisée binaire?",3,["0,99","0,90","0,60","0,01"],"La perte augmente quand le modèle attribue peu de probabilité à la classe vraie.",["Cette prédiction est presque correcte et confiante.","La probabilité de la classe vraie reste élevée.","La perte est plus forte mais modérée.","Le modèle donne presque zéro probabilité à la vraie classe."],"Entropie croisée","medium",9],
        ["À seuil 0,5, quelle probabilité correspond exactement à la frontière de décision logistique binaire?",1,["0","0,5","0,75","1"],"La frontière survient lorsque la sigmoïde renvoie le seuil.",["Cela correspond à un score tendant vers moins l'infini.","σ(0)=0,5, donc la frontière correspond au score nul.","Cela correspond à un score positif.","Cela correspond à un score tendant vers plus l'infini."],"Frontière de décision","easy",14],
        ["Les coefficients du modèle sont w=(3,4). Quelle est la norme euclidienne du vecteur normal?",0,["5","7","12","25"],"Calcule la racine carrée de la somme des carrés.",["√(3²+4²)=5, norme du vecteur normal.","7 est la somme des composantes.","12 est la somme des carrés? La somme vaut 25.","25 est la somme des carrés, pas la norme."],"Vecteur normal","medium",15],
        ["Un point a le score linéaire 10 et un autre le score 5. Pourquoi le premier n'est-il pas nécessairement deux fois plus éloigné de la frontière?",2,["Le score n'a aucun lien avec la frontière","Les deux scores sont probabilités","La distance géométrique normalise le score par la norme des coefficients","Le premier point doit être mal classé"],"Un score linéaire est une quantité non normalisée.",["Le score détermine le côté et la position relative à la frontière.","Les scores ne sont pas des probabilités.","La distance euclidienne dépend de la taille du vecteur normal.","Le signe et le seuil déterminent la classe, pas le rapport des distances."],"Score et distance","hard",16],
        ["Une sigmoïde est saturée et fournit une probabilité très proche de 0 pour une cible y=1. Quel problème la comparaison du cours met-elle en évidence avec la MSE?",3,["La MSE ne peut pas être calculée","La MSE ignore la cible","La MSE transforme la tâche en régression numérique","Le facteur de dérivée de la sigmoïde peut rendre la correction du gradient très petite"],"Songe au produit de dérivées dans la règle de chaîne.",["La perte est définie dans le cas.","La MSE compare prédiction et cible.","Le problème porte sur l'optimisation de la classification, pas sur le type d'étiquette.","La dérivée presque nulle de la sigmoïde atténue la mise à jour sous MSE."],"Gradient MSE et sigmoïde","hard",11],
        ["Pourquoi l'entropie croisée peut-elle fournir une correction plus forte à une prédiction très confiante mais fausse?",1,["Elle supprime la fonction sigmoïde","Sa dérivée par rapport au score se simplifie de façon à éviter la même atténuation problématique","Elle ne dépend pas des étiquettes","Elle remplace les coefficients par des classes"],"Le cours dérive la log-vraisemblance négative et la règle de chaîne.",["La sigmoïde reste au cœur du modèle.","La dérivation de la perte et de la sigmoïde fait apparaître une correction utile.","La cible détermine la perte.","Les coefficients restent les paramètres entraînés."],"Entropie croisée et gradient","hard",12],
        ["Le score d'un point est positif et le seuil de score correspondant à la frontière est zéro. Que peut-on conclure sur sa région prédite?",0,["Il est du côté positif de la frontière","Sa vraie étiquette est certainement positive","Il se trouve exactement sur la frontière","Sa probabilité vaut nécessairement 1"],"Le signe détermine la région du modèle lorsque le seuil est zéro.",["Un score positif est du côté positif du plan de décision.","La classe réelle peut différer de la prédiction.","Un score nul correspond à la frontière.","La sigmoïde donne une probabilité entre 0 et 1, pas nécessairement 1."],"Score et décision","medium",14],
        ["Qu'indique le vecteur normal d'une frontière linéaire?",2,["La direction parallèle à chaque bord du jeu de données","La classe vraie de chaque exemple","La direction perpendiculaire à la frontière et liée aux coefficients","Le nombre de classes"],"En géométrie, un vecteur normal est orthogonal à l'hyperplan.",["Les bords du jeu n'en définissent pas la frontière.","Le vecteur ne donne pas les étiquettes réelles.","Les coefficients forment le vecteur normal de la frontière.","Le nombre de classes n'est pas son rôle."],"Géométrie linéaire","medium",15],
        ["Pour y=0, quelle valeur de p minimise la perte binaire idéale pour cet exemple?",3,["1","0,75","0,5","0"],"Le modèle devrait attribuer une forte probabilité à l'étiquette négative.",["Cela est la confiance maximale dans la mauvaise classe.","Cela reste une probabilité excessive pour y=1.","Une prédiction indécise n'est pas idéale.","Avec y=0, une p proche de 0 minimise la perte."],"Perte binaire","easy",9],
        ["La frontière de décision a été définie par s(x)=0 pour un seuil de 0,5. On change seulement le seuil à 0,8. Que faut-il faire pour interpréter la nouvelle frontière?",1,["Réentraîner obligatoirement le modèle avant tout calcul","Résoudre s(x)=logit(0,8), ce qui déplace le niveau de score de la frontière","Remplacer le score par l'EQM","La frontière reste nécessairement au niveau s=0"],"Le seuil p se convertit en score par la sigmoïde inverse.",["Un changement de seuil seul n'exige pas un réentraînement.","Un seuil différent correspond à un niveau différent de score linéaire.","La frontière est liée au seuil et au score, pas à une nouvelle perte.","s=0 correspond spécifiquement au seuil 0,5."],"Seuil et géométrie","hard",14]
      ]
    },
    chapitre7: {
      title: "Évaluation des modèles",
      tf: [
        ["L'exactitude est la proportion totale de prédictions correctes.",true,"Elle rapporte les bonnes prédictions au nombre total de cas.","Exactitude=(VP+VN)/(VP+VN+FP+FN).","Exactitude","easy",17],
        ["La précision mesure, parmi les prédictions positives, la proportion qui est réellement positive.",true,"Son dénominateur est le nombre de prédictions positives.","Précision=VP/(VP+FP), donc elle répond à la question : parmi les positifs annoncés, combien sont corrects?","Précision","easy",19],
        ["Le rappel mesure, parmi les vrais positifs, la proportion que le modèle a retrouvée.",true,"Son dénominateur est le nombre d'exemples réellement positifs.","Rappel=VP/(VP+FN). Il mesure la part des positifs réels détectés.","Rappel","easy",21],
        ["Un faux positif est un exemple négatif que le modèle prédit positif.",true,"Le mot positif décrit la prédiction; faux indique qu'elle est incorrecte.","FP est un cas négatif selon la vérité terrain mais prédit positif.","Matrice de confusion","easy",4],
        ["Un faux négatif est un exemple positif que le modèle prédit négatif.",true,"Il s'agit d'un positif manqué.","FN représente les cas positifs que le classificateur n'a pas détectés.","Matrice de confusion","easy",4],
        ["Sur un jeu très déséquilibré, un modèle qui prédit toujours la classe majoritaire peut avoir une exactitude élevée mais une utilité médiocre.",true,"Compare le nombre de négatifs nombreux au rappel de la classe rare.","L'exactitude peut masquer un échec complet à détecter la classe minoritaire.","Déséquilibre des classes","medium",24],
        ["Le F1 combine précision et rappel à l'aide de leur moyenne arithmétique simple.",false,"La définition emploie leur moyenne harmonique.","F1=2PR/(P+R), moyenne harmonique de la précision et du rappel.","F1","medium",23],
        ["Un seuil de décision plus élevé peut diminuer le nombre de prédictions positives.",true,"Moins de scores dépasseront une barre plus haute.","À scores fixes, hausser le seuil ne peut qu'éliminer ou conserver les prédictions positives, pas en ajouter.","Seuil et métriques","medium",34],
        ["Le rappel et la précision doivent toujours augmenter ensemble lorsque le seuil change.",false,"Le compromis peut faire varier les deux métriques en directions opposées.","Un seuil plus élevé réduit souvent les faux positifs mais peut aussi augmenter les faux négatifs, donc le compromis varie.","Seuils","medium",23],
        ["Une courbe ROC relie le taux de vrais positifs au taux de faux positifs pour plusieurs seuils.",true,"Elle trace le comportement du classement lorsque le seuil varie.","Les points ROC correspondent à des seuils différents et mettent en relation TPR et FPR.","ROC","medium",36],
        ["L'AUROC résume une capacité de classement à travers les seuils plutôt qu'une seule décision à un seuil fixe.",true,"La courbe parcourt différents seuils.","L'aire sous la ROC résume la qualité de classement sur l'ensemble des seuils.","AUROC","medium",42],
        ["Une moyenne micro agrège les contributions ou décomptes avant de calculer la mesure globale.",true,"La pondération suit les nombres d'exemples ou de décisions.","La moyenne micro rassemble les décomptes des classes, donnant plus de poids aux classes plus fréquentes.","Micro et macro","medium",25],
        ["Une moyenne macro peut masquer une mauvaise performance d'une classe rare en la pondérant par son nombre d'exemples.",false,"La moyenne macro traite les classes de façon égale.","Macro calcule la mesure par classe puis en fait la moyenne non pondérée, ce qui rend les classes rares aussi influentes.","Micro et macro","medium",25],
        ["Un seuil qui maximise l'exactitude est nécessairement le meilleur choix pour chaque application.",false,"Les coûts des erreurs et l'objectif opérationnel peuvent privilégier précision ou rappel.","Le seuil dépend des conséquences des faux positifs et faux négatifs et de l'objectif visé.","Choix du seuil","hard",37],
        ["Une matrice de confusion permet de compter les erreurs de différents types au lieu de les réduire à une seule exactitude.",true,"Les cellules séparent les classes prédites et réelles.","Les décomptes VP, FP, FN et VN permettent d'interpréter les types d'erreurs.","Matrice de confusion","easy",4]
      ],
      mc: [
        ["Un classificateur prédit positif 20 fois, dont 15 sont vraiment positives. Quelle est sa précision?",0,["0,75 : 15 vrais positifs parmi 20 prédictions positives","0,25 : cinq faux positifs parmi 20 prédictions positives","0,43 : 15 vrais positifs parmi 35 exemples au total","1,33 : 20 prédictions positives divisées par 15 vrais positifs"],"Précision = vrais positifs divisés par tous les positifs prédits.",["La précision est VP/(VP+FP), donc 15/20.","Cela calcule la proportion de faux positifs parmi les positifs prédits.","Le nombre total d'exemples n'est pas fourni, et cette fraction n'est pas la précision.","Cette fraction inverse le dénominateur et le numérateur."],"Calcul de précision","easy",19],
        ["Il y a 30 cas réellement positifs, dont 24 détectés. Quel est le rappel?",0,["24/30 = 0,80","30/24 = 1,25","24/100","6/30 = 0,20"],"Le rappel divise les vrais positifs par tous les positifs réels.",["24 vrais positifs sur 30 réels donnent 0,80.","Le rappel ne peut pas dépasser 1; la fraction est inversée.","Le dénominateur doit compter les vrais positifs réels.","6 est le nombre de faux négatifs, pas de vrais positifs détectés."],"Calcul de rappel","easy",21],
        ["Une matrice compte VP=18, FP=6, FN=12, VN=64. Quelle est l'exactitude?",1,["18/36","82/100","64/82","18/24"],"Additionne les prédictions correctes VP+VN puis divise par tous les cas.",["18/36 ne compte pas tous les cas.","(18+64)/(18+6+12+64)=82/100.","Cette fraction omet les VP.","C'est la précision parmi les positifs prédits."],"Calcul d'exactitude","medium",17],
        ["Un dépistage médical veut manquer le moins de cas positifs possible. Quelle mesure est directement pertinente?",0,["Rappel","Exactitude seulement","Spécificité des négatifs uniquement","AUROC à un seuil fixe"],"Il faut réduire les faux négatifs.",["Le rappel mesure la part des positifs réels détectés.","L'exactitude peut cacher des positifs manqués.","Cette mesure porte sur les négatifs et ne répond pas directement à l'objectif.","L'AUROC résume les seuils, tandis que le besoin décrit un compromis opérationnel."],"Choix de métrique","medium",22],
        ["Dans un jeu où 99 % des exemples sont négatifs, un modèle toujours négatif obtient 99 % d'exactitude. Que montre cet exemple?",3,["Le modèle a nécessairement un rappel parfait","L'exactitude indique toujours la qualité minoritaire","Le jeu ne peut pas être évalué","Une exactitude élevée peut masquer une détection nulle de la classe positive"],"Considère les faux négatifs et la classe rare.",["Le rappel des positifs est nul.","L'exactitude n'isole pas la classe rare.","D'autres métriques peuvent évaluer ce problème.","La classe majoritaire domine le décompte total."],"Déséquilibre","medium",24],
        ["Quelle formule correspond au F1?",2,["(Précision + rappel)/2","Précision × rappel","2 × précision × rappel /(précision + rappel)","Exactitude / rappel"],"C'est la moyenne harmonique des deux mesures.",["C'est la moyenne arithmétique.","Le produit seul n'est pas la formule.","C'est la moyenne harmonique de précision et rappel.","Cette relation ne définit pas F1."],"F1","easy",23],
        ["Au seuil t, on passe de t=0,4 à t=0,8 pour les mêmes scores. Quel changement est garanti?",1,["Le nombre de positifs prédits ne peut qu'augmenter","Le nombre de positifs prédits ne peut qu'être conservé ou diminuer","Les étiquettes réelles changent","L'AUROC change nécessairement"],"Une barre plus haute élimine certains scores auparavant positifs.",["Le seuil plus strict ne crée aucun nouveau positif.","C'est l'effet monotone du seuil sur les mêmes scores.","Les cibles observées restent fixes.","L'AUROC agrège le classement sur les seuils et n'est pas modifié par la sélection d'un seuil isolé."],"Seuil","medium",34],
        ["Pour une classe rare, on calcule F1 par classe, puis on en fait une moyenne sans pondérer par le nombre d'exemples. Quelle agrégation est utilisée?",2,["Micro","Pondérée par fréquence","Macro","Exactitude globale"],"Les classes ont ici le même poids dans la moyenne finale.",["Micro agrège les décomptes.","La pondération par fréquence n'est pas égale.","Macro moyenne les scores de chaque classe de façon non pondérée.","Ce n'est pas une exactitude agrégée."],"Macro","medium",25],
        ["Quel énoncé décrit le plus justement la ROC?",3,["Le taux de faux positifs en fonction du rappel","La précision en fonction du rappel lorsque le seuil varie","La précision en fonction du taux de faux positifs","Le taux de vrais positifs en fonction du taux de faux positifs lorsque le seuil varie"],"Chaque seuil produit un point qui met en relation deux taux issus de la matrice de confusion.",["Cette option inverse les axes et emploie rappel (TPR) en abscisse.","Cela décrit la courbe précision-rappel.","La précision n'est pas l'axe vertical de la ROC.","C'est la définition fonctionnelle de la courbe ROC."],"ROC","medium",36],
        ["Deux classificateurs ont des AUROC semblables, mais l'application doit décider à un seuil donné avec un fort coût des faux négatifs. Que faut-il examiner en plus?",0,["Les métriques au seuil choisi, notamment le rappel et le nombre de faux négatifs","Seulement le score d'entraînement","Uniquement le nombre d'attributs","L'ordre alphabétique des classes"],"L'AUROC ne spécifie pas à lui seul le compromis opérationnel à un seuil.",["Le seuil et le coût des erreurs déterminent le comportement pertinent.","L'entraînement seul ne dit pas la performance aux exemples inédits.","Le nombre d'attributs ne mesure pas les conséquences d'erreur.","L'ordre des étiquettes n'est pas pertinent."],"Interprétation des métriques","hard",37]
      ]
    },
    chapitre8: {
      title: "Validation croisée et hyperparamètres",
      tf: [
        ["L'ensemble de test sert à sélectionner les hyperparamètres en comparant de nombreuses configurations.",false,"Le test final doit rester intact pendant la sélection.","La validation croisée sur l'entraînement sélectionne les configurations; le test sert à l'évaluation finale unique.","Rôle du test","easy",4],
        ["La validation croisée à k plis entraîne un nouveau modèle à chaque pli.",true,"Les paramètres appris ne se transmettent pas d'une itération à l'autre.","Chaque itération ajuste un clone neuf sur les plis d'ajustement et l'évalue sur le pli laissé de côté.","Validation croisée","easy",6],
        ["Les scores des plis d'une validation croisée sont indépendants parce que les plis de validation diffèrent.",false,"Les modèles partagent une grande partie de leurs exemples d'entraînement.","Les résultats sont liés car les jeux d'ajustement se chevauchent; l'écart-type n'est pas une erreur-type ordinaire.","Dépendance des plis","hard",6],
        ["La validation croisée améliore directement la généralisation du modèle au lieu d'aider à comparer les choix.",false,"Elle est une procédure d'estimation et de sélection.","La validation croisée estime une procédure et soutient les choix; elle n'améliore pas automatiquement le modèle.","Rôle de la validation","medium",8],
        ["Après la sélection des hyperparamètres, le modèle final peut être réajusté sur tout l'ensemble d'entraînement.",true,"La sélection est terminée avant cet ajustement final.","GridSearchCV réajuste par défaut le meilleur estimateur sur toutes les données d'entraînement.","Réajustement final","medium",21],
        ["Pour empêcher une fuite, un scaler placé dans un pipeline de validation croisée est ajusté uniquement sur chaque pli d'entraînement.",true,"Les données du pli validation doivent être transformées avec l'état appris ailleurs.","Le pipeline ajuste les étapes de prétraitement à l'intérieur de chaque pli.","Pipelines et fuite","medium",13],
        ["fit_transform sur l'ensemble complet avant la validation croisée est toujours sans fuite si le transformateur n'utilise pas y.",false,"Les attributs des futurs plis de validation influencent tout de même la transformation.","Même sans étiquettes, les statistiques calculées sur l'ensemble complet exposent les plis de validation.","Fuite de données","hard",11],
        ["transform applique des statistiques apprises précédemment sans les recalculer sur les nouvelles données.",true,"Distingue transform de fit_transform.","Les données de validation/test sont transformées avec l'état mémorisé par fit sur l'ajustement.","fit et transform","easy",12],
        ["Un hyperparamètre est toujours appris comme un coefficient à partir de la perte dans une seule configuration.",false,"Les coefficients sont paramètres; les réglages de structure sont sélectionnés en amont.","Les hyperparamètres sont choisis avant l'ajustement d'un modèle et contrôlent sa structure ou la procédure d'apprentissage.","Paramètres vs hyperparamètres","medium",15],
        ["max_depth d'un arbre, n_neighbors de KNN et C de la régression logistique sont des exemples d'hyperparamètres.",true,"Ce sont des choix de configuration évalués par sélection.","Ces exemples règlent la structure ou la régularisation et ne sont pas les coefficients ajustés directement.","Hyperparamètres","easy",15],
        ["GridSearchCV évalue systématiquement les combinaisons prédéfinies de valeurs d'hyperparamètres.",true,"Il forme le produit cartésien des valeurs candidates.","La recherche en grille évalue toutes les combinaisons fournies avec les mêmes plis et la même métrique.","Recherche en grille","easy",17],
        ["Une recherche aléatoire peut être utile lorsque l'espace de recherche contient beaucoup de combinaisons.",true,"Elle offre un budget d'itérations contrôlé.","RandomizedSearchCV échantillonne des candidates et limite le nombre de configurations testées.","Recherche aléatoire","medium",20],
        ["Utiliser le même ensemble de test à répétition pour modifier le modèle préserve son rôle d'évaluation finale indépendante.",false,"Dès que les résultats orientent des décisions, le test participe au développement.","La réutilisation adaptative transforme progressivement le test en validation et biaise l'estimation finale.","Réutilisation du test","hard",21],
        ["Une moyenne des scores de plis peut dépendre moins d'une partition unique que le score d'un seul découpage, sans rendre les plis indépendants.",true,"Il faut conserver les deux idées.","La validation croisée offre plusieurs validations, mais les jeux d'entraînement se recouvrent.","Interpréter les scores CV","hard",6],
        ["Les hyperparamètres qui interagissent devraient toujours être optimisés séparément, car leur effet ne dépend pas des autres.",false,"Une grille peut évaluer conjointement plusieurs réglages.","Des hyperparamètres peuvent interagir; il est alors utile d'évaluer leurs combinaisons.","Interaction d'hyperparamètres","medium",16]
      ],
      mc: [
        ["On veut estimer cinq fois un score de validation sans toucher au test réservé. Quelle procédure correspond le mieux?",1,["Évaluer cinq fois sur le même test et garder le meilleur score","Partitionner les données d'entraînement en cinq plis et valider chaque modèle sur un pli laissé de côté","Entraîner sur les cinq plis de validation","Calculer le score sur les exemples utilisés pour ajuster"],"Chaque pli sert une fois à la validation; le test reste hors de la procédure.",["Cela réutilise le test et crée une sélection adaptative.","C'est la validation croisée à cinq plis.","Le pli de validation est laissé de côté dans chaque ajustement.","Un score d'entraînement ne mesure pas directement la généralisation."],"Validation croisée","easy",6],
        ["Un analyste applique StandardScaler.fit_transform(X) avant de créer les plis. Quel diagnostic est correct?",3,["Aucun risque si le scaler ne regarde pas les étiquettes","Le classificateur devient non linéaire","Le test est automatiquement indépendant","Les statistiques des plis de validation ont influencé la transformation"],"Un scaler apprend des moyennes et des échelles même sans consulter y.",["Les statistiques des attributs constituent déjà de l'information.","Le type du modèle ne change pas.","La procédure de CV est contaminée.","Le prétraitement s'est ajusté avant de séparer les plis."],"Fuite de données","hard",11],
        ["Quel flux évite correctement la fuite de statistiques de prétraitement pendant une validation croisée?",0,["Ajuster le pipeline sur les plis d'entraînement de chaque itération puis utiliser transform sur le pli validation","Ajuster le scaler une fois sur toutes les données puis lancer la CV","Calculer les statistiques sur test et entraînement ensemble","Transformer le pli validation avec ses propres statistiques"],"L'ajustement des transformateurs doit suivre le découpage des plis.",["Le pipeline répète cette séparation et cet ajustement à chaque pli.","Les futurs plis de validation contribuent aux statistiques.","Le test perd son indépendance.","Le pli validation ne doit pas apprendre sa propre transformation d'évaluation."],"Pipelines","medium",13],
        ["Quel énoncé distingue correctement paramètre et hyperparamètre?",2,["Les coefficients sont des hyperparamètres; le nombre de voisins est un paramètre appris","Ce sont deux noms pour la même quantité","Les paramètres sont ajustés à partir des données; les hyperparamètres sont choisis pour régler le modèle ou l'apprentissage","Les hyperparamètres sont uniquement des étiquettes"],"Compare les poids appris au réglage n_neighbors.",["Les poids/coefs sont paramètres; le nombre de voisins est hyperparamètre.","Le cours les distingue explicitement.","C'est la distinction enseignée.","Un hyperparamètre règle le modèle, il n'est pas la cible."],"Paramètres et hyperparamètres","easy",15],
        ["On veut évaluer toutes les paires de valeurs candidates pour max_depth et criterion. Quelle méthode convient?",1,["Un seul ajustement sans validation","Une recherche en grille sur le produit des valeurs candidates","Une recherche aléatoire à budget illimité","Une prédiction sur l'ensemble test avant l'entraînement"],"Cherche une méthode qui examine systématiquement les combinaisons prédéfinies.",["Un ajustement unique ne compare pas les candidates.","GridSearchCV explore systématiquement les combinaisons.","La recherche aléatoire échantillonne et son budget est fini.","L'ordre d'entraînement-test est inversé."],"GridSearchCV","easy",17],
        ["Pourquoi les scores de plis à cinq volets ne sont-ils pas indépendants?",3,["Ils utilisent nécessairement le même pli de validation","Le modèle transfère ses poids d'un pli à l'autre","Les étiquettes sont supprimées","Les modèles ajustés partagent une grande partie de leurs exemples d'entraînement"],"Compare leurs ensembles d'ajustement, pas seulement les validations.",["Chaque pli sert une fois comme validation.","Chaque pli repart d'un modèle neuf.","Les étiquettes sont utilisées en supervisé.","Les ensembles d'ajustement se recouvrent fortement."],"Dépendance des plis","hard",6],
        ["Après avoir choisi les meilleurs hyperparamètres par validation croisée, que faire avant l'évaluation finale?",0,["Réajuster le pipeline choisi sur tout l'entraînement puis l'évaluer une seule fois sur le test intact","Réajuster le modèle sur le test","Choisir à nouveau selon le score test jusqu'à obtenir le meilleur","Mélanger les étiquettes"],"La sélection se fait d'abord sur les données d'entraînement.",["C'est le flux recommandé par le cours.","Le test ne doit pas servir à l'ajustement.","L'adaptation répétée au test le transforme en validation.","Les étiquettes sont essentielles et ne se mélangent pas arbitrairement."],"Réajustement et test final","medium",21],
        ["Un étudiant voit un score de test décevant, modifie le pipeline et le réévalue sur le même test. Quelle conséquence méthodologique?",2,["Aucune, car le pipeline n'a pas vu y","Le score devient nécessairement plus faible","Le test a influencé les choix et ne constitue plus une évaluation finale indépendante","La validation croisée devient inutile"],"Même sans ajuster directement les poids sur le test, le résultat peut guider les changements.",["Le test peut guider les choix même indirectement.","La direction du changement n'est pas garantie.","Le retour du score a contribué au développement adaptatif.","La validation croisée reste utile à la sélection."],"Réutilisation du test","hard",21],
        ["Une équipe doit comparer trois familles de modèles. Que rend la comparaison plus interprétable?",1,["Utiliser des jeux de validation, des plis et des métriques différents pour chaque candidat","Utiliser les mêmes données d'entraînement, plis de validation et métrique pour les recherches","Choisir les gagnants d'après les résultats test répétés","Utiliser seulement l'erreur d'entraînement"],"Une comparaison équitable doit limiter les différences à ce qu'on veut comparer.",["Les conditions différentes brouillent les comparaisons.","Les mêmes conditions rendent les scores comparables.","Le test ne doit pas être réutilisé pour sélectionner.","L'erreur d'entraînement ne mesure pas la généralisation."],"Comparer les modèles","medium",19],
        ["Quand RandomizedSearchCV peut-il être préférable à une recherche en grille?",3,["Lorsque chaque paramètre n'a qu'une valeur","Lorsque l'on veut examiner exhaustivement toutes les combinaisons coûte que coûte","Lorsque les modèles n'ont aucun hyperparamètre","Lorsque la grille complète est trop coûteuse et qu'on veut limiter le nombre d'essais"],"La recherche aléatoire définit un budget d'itérations.",["Il n'y a alors rien à chercher.","Une recherche aléatoire échantillonne au lieu d'être exhaustive.","Elle vise les espaces d'hyperparamètres.","Le budget contrôlé la rend utile pour de grands espaces."],"RandomizedSearchCV","medium",20]
      ]
    }
  };

  const QUESTION_BANK = Object.fromEntries(Object.entries(data).map(([key, chapter], idx) => [
    key,
    [...chapter.tf.map((r,i) => tf(idx+1,i+1,r)), ...chapter.mc.map((r,i) => mc(idx+1,i+1,r))]
  ]));
  window.QUESTION_BANK = QUESTION_BANK;
  window.CHAPTERS = Object.fromEntries(Object.entries(data).map(([key, chapter]) => [key, chapter.title]));
})();
